import { Testbase } from './testbase';

export const BASEPARATESTS2: Testbase[] = [

{ nivel:'intermedio', testID:1, testname:'VERBOS-Presente e Infinitivo 1', instruccion:'Selecciona la conjugación correcta en tiempo Presente (Select the right conjugation)',
preguntaA:'La mariposa monarca, típica de América del Norte, _________ en sus antenas una especie de "reloj" de veinticuatro (24) horas  ( verbo LLEVAR)', 
opcionA1:'llevo', opcionA2:'lleva', opcionA3:'llevan', respuestaA:'lleva', 
preguntaB:'que le _______ a __________ los cuatro mil (4.000) kilómetros  ( verbos AYUDAR y NAVEGAR)',
opcionB1:'ayuda a navegar', opcionB2:'ayudamos a navegar', opcionB3:'ayuda a navegan', respuestaB:'ayuda a navegar', 
preguntaC:'que __________ en invierno para llegar hasta México. ( verbo RECORRER)',
opcionC1:'recorro', opcionC2:'recorreré', opcionC3:'recorre', respuestaC:'recorre', 
preguntaD:'Cada otoño unas cien (100) millones de mariposas monarca _________ al sur  ( verbo EMIGRAR)', 
opcionD1:'emigran', opcionD2:'emigré', opcionD3:'emigra', respuestaD:'emigran', 
preguntaE:'__________ de acuerdo con la posición del sol,  ( verbo NAVEGAR)', 
opcionE1:'Navegamos', opcionE2:'Navegó', opcionE3:'Navegan', respuestaE:'Navegan', 
preguntaF:'ajustando sus cálculos mientras este se _______ en el cielo.  ( verbo MOVER)', 
opcionF1:'mueve', opcionF2:'muevo', opcionF3:'move', respuestaF:'mueve',
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de BURNS, J. (25 de septiembre de 2009). El GPS de las mariposas monarca. BBC News Mundo. https://www.bbc.com/mundo/ciencia-tecnologia/2009/09/090924-1700-mariposa-monarca_gtg',
pubTest:''
},

{nivel:'intermedio', testID:2, testname:'VERBOS-Presente e Infinitivo 2', instruccion:'Selecciona la conjugación correcta en tiempo Presente (Select the right conjugation)',
preguntaA:'Los colibríes _______  _______ de un lado a otro, hacia atrás e incluso quedarse suspendidos en un punto.( verbos PODER y VOLAR Presente e Infinitivo) ', 
opcionA1:'puedes vuelan', opcionA2:'pueden volar',opcionA3:'pueden vuelan',respuestaA:'pueden volar', 
preguntaB:'En el mundo de las aves, los colibríes ________  el record del aleteo más veloz,( verbo OSTENTAR )', 
opcionB1:'ostentan', opcionB2:'ostentar', opcionB3:'ostenta', respuestaB:'ostentan', 
preguntaC:' ________ las alas 40-50 veces por segundo y algunas especies hasta 80 veces. ( verbo MOVER) ', 
opcionC1:'mueves', opcionC2:'mueven', opcionC3:'muevo', respuestaC:'mueven',
preguntaD:'El truco para volar como un colibrí _______ en ser el pájaro más pequeño de todos, ( verbo ESTAR )', 
opcionD1:'estoy',opcionD2:'están', opcionD3:'está', respuestaD:'está', 
preguntaE:'así como el pájaro que ________ más rápido ( verbo ALETEAR )', 
opcionE1:'aletea', opcionE2:'aletean', opcionE3:'aleteamos',  respuestaE:'aletea', 
preguntaF:'Los colibríes _________ su peso corporal en néctar cada día para suplir su costo corporal energético. (  verbos CONSUMIR )', 
opcionF1:'consumo', opcionF2:'consumen', opcionF3:'consumir', respuestaF:'consumen', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de CUSÓ,Ò.(21 de noviembre de 2022).Desvelando los secretos del vuelo de los colibríes en súper \'slow motion\'. NATIONAL GEOGRAPHIC España. https://www.nationalgeographic.com.es/naturaleza/desvelando-vuelo-colibries-super-slow-motion-15701',
pubTest:''
},

{nivel:'intermedio', testID:3, testname:'VERBOS-Pretérito (Perfecto e Imperfecto) 1', instruccion:'Selecciona la conjugación correcta (Select the right conjugation)',
preguntaA:'Algunos de los estudios de observación elaborados cincuenta (50) años atrás, indicaron que cuando se les __________ las antenas  ( verbos QUITAR-Pretérito Imperfecto)', 
opcionA1:'quité', opcionA2:'quitaban',opcionA3:'quitaste',respuestaA:'quitaban', 
preguntaB:'las mariposas __________ de _______ en la dirección correcta  ( verbos DEJAR y VOLAR -Pretérito Imperfecto)', 
opcionB1:'dejabas de volaban', opcionB2:'dejaban de volar', opcionB3:'dejé de volar', respuestaB:'dejaban de volar', 
preguntaC:'Los expertos quitaron las antenas a un grupo de mariposas y ___________  ( verbo COMPARAR-Pretérito Perfecto)', 
opcionC1:'compararon', opcionC2:'comparar', opcionC3:'comparé', respuestaC:'compararon',
preguntaD:'la forma en que las mariposas __________ con la de un grupo controlado en un simulador de vuelo ( verbo VOLAR-Pretérito Imperfecto)', 
opcionD1:'volábamos',opcionD2:'volaba', opcionD3:'volaban', respuestaD:'volaban', 
preguntaE:'Todas las mariposas intactas __________ al suroeste, como ocurre normalmente, ( verbo VOLAR-Pretérito Perfecto)', 
opcionE1:'volamos', opcionE2:'volaron', opcionE3:'volé',  respuestaE:'volaron', 
preguntaF:'pero las mariposas sin antena, aunque también volaron, lo _________ en distintas direcciones. ( verbo HACER-Pretérito Perfecto)', 
opcionF1:'hicieron', opcionF2:'hice', opcionF3:'hizo', respuestaF:'hicieron', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de BURNS, J. (25 de septiembre de 2009). El GPS de las mariposas monarca. BBC News Mundo. https://www.bbc.com/mundo/ciencia-tecnologia/2009/09/090924-1700-mariposa-monarca_gtg',
pubTest:''
},

{nivel:'intermedio', testID:4, testname:'VERBOS-Pretérito (Perfecto e Imperfecto) 2', instruccion:'Selecciona la conjugación correcta (Select the right conjugation)',
preguntaA:'El emperador Julio César, hace casi 2.000 años, ________ un calendario muy parecido al que utilizamos hoy en día ( verbo IMPONER Pretérito Perfecto) ', 
opcionA1:'impusieron', opcionA2:'impuso',opcionA3:'impuse',respuestaA:'impuso', 
preguntaB:'El llamado calendario juliano _________ los 12 meses con 30 y 31 días, iniciando el año en marzo, por ser el comienzo de la primavera  ( verbo ALTERNAR Pretérito Perfecto )', 
opcionB1:'alternó', opcionB2:'alterné', opcionB3:'alternaste', respuestaB:'alternó', 
preguntaC:'El calendario juliano ________ durante siglos, pero no es exacto porque el año solar en realidad es un poco más corto: 11 minutos y 14.784 segundos. ( verbo SERVIR Pretérito Perfecto) ', 
opcionC1:'sirvió', opcionC2:'serviste', opcionC3:'servían', respuestaC:'sirvió',
preguntaD:'Para corregir el desfase el papa Gregorio XIII __________ con su calendario gregoriano en 1582. ( verbo INTERCEDER Pretérito Perfecto )', 
opcionD1:'intercediste',opcionD2:'intercedió', opcionD3:'intercedí', respuestaD:'intercedió', 
preguntaE:'Entonces para instaurar el calendario, los gobernantes en el año 1582 ___________, en lugar de eliminar años bisiestos en las siguientes cuatro décadas, ( verbo DECIDIR Pretérito Perfecto)', 
opcionE1:'decidí', opcionE2:'decidió', opcionE3:'decidieron',  respuestaE:'decidieron', 
preguntaF:'ellos ________ 10 días y ________ del jueves, 5 de octubre, al viernes 14 de octubre de 1582. (  verbos CORTAR y SALTAR Pretérito Perfecto )', 
opcionF1:'cortaron - saltaron', opcionF2:'corté - salté', opcionF3:'cortaste - saltaste', respuestaF:'cortaron - saltaron', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de BBC.(28 de febrero de 2020). 30 de febrero, el día que solo existió una vez en la historia. Semana.com. https://www.semana.com/vida-moderna/articulo/30-de-febrero-el-dia-que-solo-existio-una-vez-en-la-historia/654452/',
pubTest:''
},

{nivel:'intermedio', testID:5, testname:'VERBOS-Pretérito (Perfecto e Imperfecto) 3', instruccion:'Selecciona la conjugación correcta (Select the right conjugation)',
preguntaA:'En 1946 el cocodrilo Saturno _______ a vivir al zoológico de Moscú ( verbo LLEGAR Pretérito Perfecto) ', 
opcionA1:'llegó', opcionA2:'llegué',opcionA3:'llegaron',respuestaA:'llegó', 
preguntaB:'y ______ todo un acontecimiento porque por aquel entonces solo había dos cocodrilos en la capital soviética ( verbo SER Pretérito Perfecto )', 
opcionB1:'ser', opcionB2:'fuí', opcionB3:'fue', respuestaB:'fue', 
preguntaC:'a Saturno le ________ _________ (verbos GUSTAR y DORMIR - Pretérito Imperfecto) ', 
opcionC1:'gustó dormía', opcionC2:'gustaba dormir', opcionC3:'gustaba dormía', respuestaC:'gustaba dormir',
preguntaD:'y no _____ exigente con el menú, le gustaba comer pescado, conejo y ratas (verbo SER Pretérito Imperfecto )', 
opcionD1:'eras',opcionD2:'eran', opcionD3:'era', respuestaD:'era', 
preguntaE:' Saturno era muy tranquilo, apenas ___________ altercados ( verbo OCASIONAR Pretérito Perfecto)', 
opcionE1:'ocasionó', opcionE2:'ocasioné', opcionE3:'ocasionaste',  respuestaE:'ocasionó', 
preguntaF:'En 2020 el zoológico de Moscú __________ la muerte de Saturno. (  verbos ANUNCIAR Pretérito Perfecto )', 
opcionF1:'anuncié', opcionF2:'anunció', opcionF3:'anunciaron', respuestaF:'anunció', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de COLÁS, X.(24 de mayo de 2020). Muere \'Saturno\', el cocodrilo que conoció a Hitler y escapó durante los bombardeos de Berlín. https://www.elmundo.es/ciencia-y-salud/ciencia/2020/05/23/5ec9759221efa0f26a8b4638.html',
pubTest:''
},

{nivel:'intermedio', testID:6, testname:'Pronombres reflexivos y adjetivos posesivos', instruccion:'Selecciona los pronombres y adjetivos correctos (Select the right options)',
preguntaA:'Yo ____ llevo bien con ____ (my) padre porque nosotros tenemos el mismo sentido de humor', 
opcionA1:'te   -    mi', opcionA2:'me   -    mi',opcionA3:'me   -    tu',respuestaA:'me   -    mi', 
preguntaB:'Ella ____ lleva bien con ____ (her) padre porque ellos tienen el mismo sentido de humor', 
opcionB1:'me   -    su', opcionB2:'se   -    sus', opcionB3:'se   -    su', respuestaB:'se   -    su', 
preguntaC:'Ellos no ____ llevan bien con ____ (their) padres', 
opcionC1:'se   -    sus', opcionC2:'ses   -    sus', opcionC3:'se   -    tus', respuestaC:'se   -    sus',
preguntaD:'Ellos no ____ llevan bien con ____ (their) padre', 
opcionD1:'se   -    sus',opcionD2:'se   -    su', opcionD3:'ses   -    su', respuestaD:'se   -    su', 
preguntaE:'¿Con quién ____ llevas mejor tú?. Con ____ (your) padre o con ___ (your) madre', 
opcionE1:'te  -  tú   -  tú', opcionE2:'se  -  su   -  su', opcionE3:'te  -  tu   -  tu',  respuestaE:'te  -  tu   -  tu', 
preguntaF:'Todos ellos ____ llevan muy mal con ____ (their)profesor', 
opcionF1:'se   -    su', opcionF2:'se   -    sus', opcionF3:'ses   -    su', respuestaF:'se   -    su', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},

{nivel:'intermedio', testID:7, testname:'VERBOS Reflexivos - Futuro ', instruccion:'Selecciona la conjugación correcta en tiempo Futuro (Select the right conjugation)',
preguntaA:'Yo ____  ________ (verbo QUEDARSE) en casa', 
opcionA1:'me quedaré', opcionA2:'te quedaré',opcionA3:'me quedé',respuestaA:'me quedaré', 
preguntaB:'Ella  ____  ________  (verbo MAQUILLARSE) para ir a la fiesta', 
opcionB1:'se maquillarán', opcionB2:'se maquillará', opcionB3:'te maquillarás', respuestaB:'se maquillará', 
preguntaC:'Ellos  ____  ________  (verbo ENCARGARSE) de hacer todas las tareas', 
opcionC1:'se encargaron', opcionC2:'te encargarás', opcionC3:'se encargarán', respuestaC:'se encargarán',
preguntaD:'Ellos no ____  _________  (verbo SEPARARSE) durante la excursión ', 
opcionD1:'se separaron',opcionD2:'se separarán', opcionD3:'te separaste', respuestaD:'se separarán', 
preguntaE:'Nosotros ____  _________ (verbo DESPERTARSE) temprano mañana', 
opcionE1:'nos despertaremos', opcionE2:'nos despertamos', opcionE3:'me despertaré',  respuestaE:'nos despertaremos', 
preguntaF:'Todos ____  _________ (verbo DUCHARSE) antes de entrar en la piscina', 
opcionF1:'te ducharás', opcionF2:'se ducharán', opcionF3:'me ducharé', respuestaF:'se ducharán', 
preguntaG:'Tú ____  _________ (verbo SORPRENDERSE) con el resultado', 
opcionG1:'te sorprenderás', opcionG2:'te sorprendiste', opcionG3:'se sorprenderá', respuestaG:'te sorprenderás', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},

{nivel:'intermedio', testID:8, testname:'Verbo IR A + Infinitivo', instruccion:'Sustituye el verbo en Futuro por la expresión IR A + infinitivo (Select the right conjugation)',
preguntaA:'Yo me quedaré en casa', 
opcionA1:'nos vamos a quedar', opcionA2:'te vas a quedar',opcionA3:'me voy a quedar',respuestaA:'me voy a quedar', 
preguntaB:'Ella se maquillará para ir a la fiesta', 
opcionB1:'se van a maquillar', opcionB2:'se va a maquillar', opcionB3:'te vas a maquillar', respuestaB:'se va a maquillar', 
preguntaC:'Ellos se encargarán de hacer todas las tareas', 
opcionC1:'se van a encargar', opcionC2:'te vas a encargar', opcionC3:'nos vamos a encargar', respuestaC:'se van a encargar',
preguntaD:'Ellos no se separarán durante la excursión ', 
opcionD1:'no nos vamos a separar',opcionD2:'no se va a separar', opcionD3:'no se van a separar', respuestaD:'no se van a separar', 
preguntaE:'Nosotros nos despertaremos temprano mañana', 
opcionE1:'voy a despertar', opcionE2:'nos vamos a despertar', opcionE3:'se van a despertar',  respuestaE:'nos vamos a despertar', 
preguntaF:'Todos se ducharán antes de entrar en la piscina', 
opcionF1:'se van a duchar', opcionF2:'me voy a duchar', opcionF3:'te vas a duchar', respuestaF:'se van a duchar', 
preguntaG:'Tú te sorprenderás con el resultado', 
opcionG1:'se va a sorprender', opcionG2:'nos vamos a sorprender', opcionG3:'te vas a sorprender', respuestaG:'te vas a sorprender', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:'Test patrocinado por Prof. Javier Díaz - Tutor de Español en Preply.com - contactar en https://preply.com/en/tutor/232026'
},

{nivel:'intermedio', testID:9, testname:'Adverbios de lugar', instruccion:'La estación del tren queda al lado derecho del centro comercial. La universidad y el museo quedan al lado izquierdo del centro comercial. El museo es un edificio muy pequeño que está delante de la universidad. El aeropuerto queda en el otro extremo de la ciudad. En el centro comercial hay un cine en el primer piso y una tienda de ropa en el segundo piso y tiene un estacionamiento en el sótano.',
preguntaA:'La universidad está __________  del museo', 
opcionA1:'ENCIMA', opcionA2:'CERCA',opcionA3:'DEBAJO',respuestaA:'CERCA', 
preguntaB:'El aeropuerto está ________ de la estación del tren', 
opcionB1:'AL LADO', opcionB2:'EN FRENTE', opcionB3:'LEJOS', respuestaB:'LEJOS', 
preguntaC:'El cine está ________ del centro comercial', 
opcionC1:'DENTRO', opcionC2:'FUERA', opcionC3:'ENTRE', respuestaC:'DENTRO',
preguntaD:'La tienda de ropa está ________ del cine', 
opcionD1:'LEJOS',opcionD2:'DELANTE', opcionD3:'ENCIMA', respuestaD:'ENCIMA', 
preguntaE:'El estacionamiento del centro comercial está _________ del cine', 
opcionE1:'EN FRENTE', opcionE2:'DEBAJO', opcionE3:'LEJOS',  respuestaE:'DEBAJO', 
preguntaF:'El centro comercial queda _________ la estación del tren y la universidad', 
opcionF1:'ENTRE', opcionF2:'DENTRO', opcionF3:'ENCIMA', respuestaF:'ENTRE', 
preguntaG:'La universidad está ________ del museo', 
opcionG1:'DETRÁS', opcionG2:'DELANTE', opcionG3:'DEBAJO', respuestaG:'DETRÁS', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},

{nivel:'intermedio', testID:10, testname:'Imperativos / Pronombres de Complemento Directo o Indirecto', instruccion:'Seleccione la opción correcta (Select the right option)',
preguntaA:'La máquina se desvió del camino, ___________ (TÚ - REDIRIGIR)', 
opcionA1:'redirígelos', opcionA2:'redirígela',opcionA3:'redirígelas',respuestaA:'redirígela', 
preguntaB:'Las piedras están obstruyendo el camino, _________ (USTEDES - RECOGER) todas y _______ (USTEDES - LLEVAR) a otro sitio', 
opcionB1:'recójanlas - llévenlas', opcionB2:'recójanlos - llévenlos', opcionB3:'recógeme - llévame', respuestaB:'recójanlas - llévenlas', 
preguntaC:'___________ (TÚ - CONTAR - A MÍ) un cuento, por favor', 
opcionC1:'cuéntame', opcionC2:'cuéntenme', opcionC3:'cuéntale', respuestaC:'cuéntame',
preguntaD:'Las personas están en peligro por la erupción del volcán, ________ (USTEDES - EVACUAR) de inmediato', 
opcionD1:'evacúalas',opcionD2:'evacúenlo', opcionD3:'evacúenlas', respuestaD:'evacúenlas', 
preguntaE:'El oso está en frente __________ (NOSOTROS - QUEDARSE) muy quietos para _________ (EVITAR-infinitivo -A ÉL)', 
opcionE1:'quedémonos - evitarlo', opcionE2:'quédense - evítalo', opcionE3:'quedémonos - evítenlo',  respuestaE:'quedémonos - evitarlo', 
preguntaF:'El arrecife de coral es maravilloso (TÚ - SUMERGIR) para que puedas _____ (VER-infinitivo - A Él)', 
opcionF1:'sumérgete - verlo', opcionF2:'sumérgirme - verlo', opcionF3:'sumérgete - verlo', respuestaF:'sumérgete - verlo', 
preguntaG:'La ropa es de ella, ____________ (USTEDES - DEVOLVER - A ELLA)', 
opcionG1:'devuélvesela', opcionG2:'devuélvanmela', opcionG3:'devuélvansela', respuestaG:'devuélvansela', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},


];

