import { Testbase } from './testbase';

export const BASEPARATESTS3: Testbase[] = [

{nivel:'avanzado', testID:1, testname:'El Asteroide que acabó con los dinosaurios', instruccion:'',
preguntaA:'Hace 66 millones de años, un asteroide gigante se estrelló contra la Tierra y ______ un cráter de más de 177 km de diámetro en la Península de Yucatán, en lo que hoy es la ciudad mexicana de Chicxulub',
opcionA1:'dejó', opcionA2:'dejamos',opcionA3:'dejé',respuestaA:'dejó', 
preguntaB:'El asteroide hizo que los mares absorbieran una parte de los gases de efecto invernadero emitidos por una meseta volcánica en la antigua India conocida como las Traps del Decán -o escaleras del Decán-, y esto logró atenuar el calentamiento que, de otro modo, podría haber perjudicado a los primeros mamíferos y muchas de las otras especies que sobrevivieron el impacto. Pregunta: ¿Qué provocó el asteroide?', 
opcionB1:'que la meseta volcánica dejara de emitir gases de efecto invernadero', opcionB2:'que los mares absorbieran parte de los gases de efecto invernadero', opcionB3:'ninguna de las anteriores', respuestaB:'que los mares absorbieran parte de los gases de efecto invernadero', 
preguntaC:'¿Ninguna especie animal sobrevivió al asteroide hace 66 millones de años?',
opcionC1:'Verdadero', opcionC2:'Falso', opcionC3:'No puedo saberlo',  respuestaC:'Falso', 
preguntaD:'Los investigadores creen que el asteroide fue el único causante de la extinción de los dinosaurios, pero también creen que su efecto en el plancton oceánico puede haber disminuido el posterior calentamiento global provocado por las erupciones volcánicas, que continuaron durante otros 300.000 años. Pregunta: ¿El asteroide detuvo las erupciones volcánicas de la época?', 
opcionD1:'Verdadero', opcionD2:'Falso', opcionD3:'No puedo saberlo', respuestaD:'Falso',
preguntaE:'¿El asteroide mitigó el calentamiento global de la época?', 
opcionE1:'Verdadero', opcionE2:'Falso', opcionE3:'No puedo saberlo', respuestaE:'Verdadero', 

preguntaF:'', opcionF1:'', opcionF2:'', opcionF3:'', respuestaF:'', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de VERNIMMEN, T.(3 de marzo de 2020). El asteroide que acabó con los dinosaurios permitió la supervivencia de otras especies. NATIONAL GEOGRAPHIC. https://www.nationalgeographicla.com/ciencia/2020/01/el-asteroide-que-acabo-con-los-dinosaurios',
pubTest:''
},


{nivel:'avanzado', testID:2, testname:'La búsqueda del tesoro ha terminado', instruccion:'',
preguntaA:'La larga búsqueda del tesoro, que en la última década llevó a miles personas al oeste de EE.UU. y causó al menos cuatro muertes, ha terminado. Un aventurero encontró el cofre con joyas que el millonario coleccionista de antigüedades Forrest Fenn enterró en el oeste del país y sobre el cual dio pistas en un libro publicado en 2010. Pregunta: ¿Cuánto tiempo permaneció escondido el tesoro?',
opcionA1:'100 años', opcionA2:'cuatro décadas',opcionA3:'una década',respuestaA:'una década', 
preguntaB:'El propio Fenn confirmó en su sitio web que un hombre del "este" de EE.UU. dio con el cofre el pasado sábado 6 de junio. "Estaba bajo un dosel de estrellas en la exuberante vegetación boscosa de las Montañas Rocosas y no se había movido del lugar donde lo escondí hace más de 10 años", escribió el millonario de 89 años. Fenn también le dijo al periódico The Santa Fe New Mexican que el hombre no quería que se divulgara su nombre, pero había confirmado el hallazgo enviando una fotografía. Pregunta: ¿Quién descubrió el tesoro?', 
opcionB1:'un fotógrafo de Santa Fe', opcionB2:'el descubridor se mantiene anónimo', opcionB3:'un hombre del sur de EE.UU', respuestaB:'el descubridor se mantiene anónimo', 
preguntaC:'Un poema de 24 versos tenía las nueve pistas para hallar el tesoro. Cuando se le preguntó cómo se sentía acerca del tesoro que se encontró, Fenn dijo al periódico: "No sé, me siento medio feliz, medio triste, porque la búsqueda ha terminado". Pregunta: ¿Dónde estaban las pistas?', 
opcionC1:'Las pistas eran enviadas por correo electrónico', opcionC2:'Las pistas salían en un periódico de Santa Fe', opcionC3:'Las pistas estaban en un poema', respuestaC:'Las pistas estaban en un poema',
preguntaD:'No todo fue diversión y aventura durante la búsqueda. La División de Búsqueda y Rescate de Nuevo México reportó casos de extravíos de personas que se internaron en las montañas de Santa Fe motivados por el libro. Pregunta: ¿Qué ha reportado la División de Búsqueda y Rescate de Nuevo México?', 
opcionD1:'personas extraviadas durante la búsqueda',opcionD2:'mucho interés en la búsqueda del tesoro', opcionD3:'alto volúmen de excursionistas', respuestaD:'personas extraviadas durante la búsqueda', 
preguntaE:'', opcionE1:'', opcionE2:'', opcionE3:'',  respuestaE:'', 
preguntaF:'', opcionF1:'', opcionF2:'', opcionF3:'', respuestaF:'', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de REDACCION BBC News Mundo. (8 de junio de 2020). Tesoro de Forrest Fenn: el hallazgo del codiciado cofre escondido en las Montañas Rocosas y que fue buscado por miles durante una década. BBC News Mundo. https://www.bbc.com/mundo/noticias-52971996',
pubTest:''
},

{nivel:'avanzado', testID:3, testname:'El Cuaderno Letal de Marie Curie', instruccion:'',
preguntaA:'La científica Marie Curie ganó el Premio Nobel en dos campos diferentes, física y química, y desarrolló la teoría de la radiactividad. Pregunta: ¿Quién fue Marie Curie?',
opcionA1:'una astronauta', opcionA2:'una científica',opcionA3:'una paciente',respuestaA:'una científica', 
preguntaB:'Debido a la constante manipulación de material radiactivo sin el equipo recomendado y por guardar tubos de ensayo con radio en los bolsillos. Sus posesiones terminaron gravemente contaminadas. Pregunta: ¿Cómo manipuló Marie Curie el material radiactivo?', 
opcionB1:'utilizando el equipo apropiado', opcionB2:'sin utilizar el equipo apropiado', opcionB3:'nunca manipuló material radiactivo', respuestaB:'sin utilizar el equipo apropiado', 
preguntaC:'Sus objetos personales, ropa, libros, cuadernos, son considerados como tesoros nacionales y científicos, y están almacenados en cajas forradas con plomo en la Biblioteca Nacional de Francia en París y requieren un equipo especial para aquellos investigadores que quieran consultar sus notas. Pregunta: ¿Cómo están almacenados los objetos personales de Marie Curie?', 
opcionC1:'en cajas forradas con plomo', opcionC2:'en la Biblioteca Nacional de Francia en París', opcionC3:'ninguna de las anteriores', respuestaC:'en cajas forradas con plomo',
preguntaD:'¿Dónde están almacenados los objetos personales de Marie Curie?', 
opcionD1:'sin equipos especiales de protección', opcionD2:'en la Biblioteca Nacional de Francia en París', opcionD3:'en el país natal de Marie Curie', respuestaD:'en la Biblioteca Nacional de Francia en París', 
preguntaE:'Los objetos están contaminados con el radio 226, que tiene una vida media de 1.600 años. Habrá que esperar otros 1.500 años más para que se elimine a la mitad su nivel de radiactividad. Pregunta:¿Cómo será el nivel de radiactividad de esos objetos dentro de 1.500 años?',
opcionE1:'será igual al nivel actual', opcionE2:'será el doble del nivel actual', opcionE3:'será la mitad del nivel actual',  respuestaE:'será la mitad del nivel actual', 
preguntaF:'', opcionF1:'', opcionF2:'', opcionF3:'', respuestaF:'', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de ABC.ES (28 de junio de 2018). El letal cuaderno de Marie Curie que puede matarte con el mero contacto incluso 100 años después. ABC Historia. https://www.abc.es/historia/abci-letal-cuaderno-marie-curie-puede-matarte-mero-contacto-incluso-100-anos-despues-201704091801-noticia.html',
pubTest:''
},

{nivel:'avanzado', testID:4, testname:'El oporto - nuevos paladares', instruccion:'',
preguntaA:'Aunque puede que en las latitudes más frías se siga sacando una botella de oporto con ocasión de Navidad, quedan lejanos los días en que este vino era parte habitual de la sobremesa, al menos para la mayoría. Portugal ve cómo la renovación de la imagen del tradicional vino fortificado está afectando el histórico comercio en el valle del Alto Duero. Pregunta: ¿Dónde se ha comerciado históricamente el oporto?', 
opcionA1:'En ocasión de navidad', opcionA2:'En el valle del Alto Duero',opcionA3:'En las sobremesas habituales',respuestaA:'En el valle del Alto Duero', 
preguntaB:'Paul Symington camina por sus viñedos en la ladera de una colina, a gusto con su tierra. Con cada paso, firme sobre el suelo _________ y resbaladizo, se perfila cual general romano. Se detiene para conversar con sus hombres en la viña.', 
opcionB1:'firmeza', opcionB2:'secar', opcionB3:'húmedo', respuestaB:'húmedo', 
preguntaC:'Consulta con su caseiro, quien administra la viña, pregunta a un joven analista sobre la calidad del suelo, y luego recorre con la mirada su propiedad, donde la niebla esconde las vistas del río Duero, que corre por debajo. "Los romanos se vestían distinto, por supuesto. Y no hubieran llegado en coche", dice. "Pero aparte de eso, lo que se ve por aquí no ha cambiado desde la época del imperio romano", afirma.  Pregunta: ¿Qué comentario hace el propietario sobre sus viñedos?', 
opcionC1:'Que están analizando el suelo del viñedo', opcionC2:'Que desde allí son hermosas las vistas del Valle del Duero', opcionC3:'Que no han cambiado desde la época del imperio romano',respuestaC:'Que no han cambiado desde la época del imperio romano',
preguntaD:'Su familia lleva más de 300 años podando las viñas del norte de Portugal. Paul tiene un sentido instintivo sobre la historia y la tradición, pero sabe que las cosas deben cambiar si el negocio familiar ha de sobrevivir. Pregunta: ¿Qué opina el propietario de su negocio familiar?', 
opcionD1:'Que debe cambiar para poder sobrevivir',opcionD2:'Que debe mantener su historia y tradición ', opcionD3:'Que se ha conservado igual en 300 años', respuestaD:'Que debe cambiar para poder sobrevivir', 
preguntaE:'El negocio de esta región es el oporto, y si un licor está ________ su imagen es este vino espirituoso color rubí. El oporto te hace imaginar profundas bodegas con añejos barriles cubiertos de telarañas; un brindis tras una victoria militar; extraños rituales con licoreras de cristal y conversaciones entre coroneles de nariz y cachetes colorados.', 
opcionE1:'renovando', opcionE2:'imitando', opcionE3:'evitando',  respuestaE:'renovando', 
preguntaF:'Paul ha debido pensar muy seriamente sobre su futuro. "Hay una ceremonia maravillosa asociada al oporto", dice. "En los banquetes de Estado, la reina de Inglaterra brinda con oporto, y no queremos que eso se ______________", afirma.', 
opcionF1:'encuentre', opcionF2:'robe', opcionF3:'pierda', respuestaF:'pierda', 
preguntaG:'"Pero hoy por hoy la gente vive distinto. No tenemos bodegas en casa. Comemos en la cocina. No nos vestimos para cenar cada noche", señala. "Debemos adaptarnos a nuestros mercados. Definitivamente _______________ que la gente joven beba oporto", indica.',
opcionG1:'necesitamos', opcionG2:'exigimos', opcionG3:'rezamos', respuestaG:'necesitamos', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de HAWKSLEY, H. (21 de diciembre de 2009). El oporto en busca de nuevos paladares. BBC News Mundo. https://www.bbc.com/mundo/cultura-sociedad/2009/12/091221-1800-oporto-navidad-med',
pubTest:''
},

{nivel:'avanzado', testID:5, testname:'Los números en el triángulo de reciclaje', instruccion:'',
preguntaA:'Una botella de plástico puede tardar años en descomponerse e incluso entonces muchos de los componentes de la misma nunca se _________ completamente. Varios productos plásticos están identificados con un número dentro del símbolo de reciclaje. Este número indica el tipo de plástico del cual está hecho el producto.',
opcionA1:'desharán', opcionA2:'deshacer',opcionA3:'crearán',respuestaA:'desharán', 
preguntaB:'Los plásticos marcados con un número 1 están hechos de polietileno tereftalato, también conocido como PETE o PET. Éste es encontrado en las botellas de agua y refrescos, en algunos recipientes de medicina, en los enjuagues bucales, en los contenedores de mantequilla de maní y en los de aderezos para ensaladas y aceites vegetales. Los plásticos marcados con un número 1 son los más fáciles de reciclar y son muy solicitados por los fabricantes. Este plástico es muy ________  por las entidades de reciclado y los programas callejeros de reciclado.', 
opcionB1:'cambiado', opcionB2:'rechazado', opcionB3:'aceptado', respuestaB:'aceptado', 
preguntaC:'Los plásticos número 2 son de polietileno de alta densidad, o HDPE. Algunos ejemplos son las botellas de champú, los  ___________  de mantequilla y yogur, y las botellas usadas para la lejía, el jabón para lavarropas y el aceite de motor. Al ser reciclado, el HDPE puede ser usado en juguetes, cerámicas para el piso, mesas de picnic, soga plástica y cercas.', 
opcionC1:'cajas', opcionC2:'recipientes', opcionC3:'botellas', respuestaC:'recipientes',
preguntaD:'Los plásticos tipo 3 son cloruro de polivinilo, o PVC. Éste es comúnmente asociado con los tubos PVC disponibles para los proyectos hogareños. También es utilizado en las cortinas para baño, en las tetinas de los biberones. ___________, el PVC es difícil de reciclar.', 
opcionD1:'Desafortunadamente',opcionD2:'Nunca', opcionD3:'Ocasionalmente', respuestaD:'Desafortunadamente', 
preguntaE:'Los plásticos marcados con un número 4 son polietileno de baja densidad, o LDPE. Este plástico es usado en las bolsas de las compras y bolsas para pan y sándwich, en las botellas que pueden apretarse, y en ropa, alfombras y muebles. El LDPE es difícil de reciclar. Los compradores pueden _________  el número de bolsas de compras en los basureros rechazándolas en las tiendas y llevando en su lugar su propia bolsa para compras reusable.', 
opcionE1:'multiplicar', opcionE2:'disminuir', opcionE3:'llevar',  respuestaE:'disminuir', 
preguntaF:'Los plásticos número 5 son polipropileno, o PP. Este tipo de plástico es usado para hacer recipientes de comida, botellas de salsa de tomate y sirope, pajitas y tapas plásticas para botellas. Los plásticos tipo 6 están hechos de poliestireno (PS), estos elementos incluyen las tazas de café, platos y utensilios descartables. El polipropileno y el poliestireno son difíciles de reciclar, aunque son ocasionalmente aceptados a través de programas callejeros de reciclaje, así como ________  en algunos centros de reciclado.',
opcionF1:'cuando', opcionF2:'nunca', opcionF3:'también', respuestaF:'también', 
preguntaG:'El tipo 7 es el plástico más difícil de reciclar, incluye los botellones de agua de 3 y 5 galones, los materiales antibalas, los DVD, las computadoras, etc. Algunos plásticos tipo 7 son únicamente reciclados por artistas que __________ maneras de convertir los materiales en nuevos objetos.', 
opcionG1:'encuentran', opcionG2:'cambian', opcionG3:'sienten', respuestaG:'encuentran', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de ROGIER, M. (20 de noviembre 2021). ¿Qué significan los números en el triángulo de reciclaje de los plásticos?. eHowenEspañol.https://www.ehowenespanol.com/significan-numeros-triangulo-reciclaje-plasticos-sobre_118374',
pubTest:''
},


{ nivel:'avanzado', testID:6, testname:'Dante volverá a Florencia', instruccion:'',
preguntaA:'Tras una batalla de siete siglos con Rávena, donde se encuentra ____________ el Poeta, los alcaldes negocian su «regreso».', 
opcionA1:'peleando', opcionA2:'viviendo', opcionA3:'enterrado', respuestaA:'enterrado', 
preguntaB:'Está a punto de acabar el exilio de Dante Alighieri (Florencia, 1265 - Rávena, 1321), llamado en Italia «Sommo Poeta» (Poeta Supremo), el padre de la lengua italiana. Se terminará así una guerra que dura casi siete siglos entre Florencia y Rávena. La aspiración de la capital de la región de Toscana desde hace siglos es llevar a Florencia a su figura más ilustre del pasado, la misma Florencia que en vida lo había echado y condenado al exilio. Negocian con gran discreción los alcaldes de Florencia y Rávena para que el Divino Poeta retorne en coincidencia con el 700 aniversario de su muerte, que será en el 2021.  Pregunta: ¿Dónde murió Dante Alighieri?',
opcionB1:'Florencia', opcionB2:'Rávena', opcionB3:'Toscana', respuestaB:'Rávena', 
preguntaC:'La decisión está en manos de Rávena, donde el autor de la Divina Comedia murió. Su tumba en la basílica de San Francisco es visitada cada año por miles de turistas, por lo que Rávena nunca ha querido perder ese tesoro. Concretamente, los visitantes italianos y extranjeros de la tumba de Dante desde 2016 superan una media de 400.000 anualmente. Así que Rávena no renunciará al privilegio de ser referencia importante sobre el poeta, escritor y político italiano. Pregunta: ¿Por qué Rávena no ha devuelto el cuerpo de Dante a Florencia en 700 años?',
opcionC1:'Porque no saben dónde está el cuerpo', opcionC2:'Porque Florencia no ha pagado', opcionC3:'Porque atrae turistas', respuestaC:'Porque atrae turistas', 
preguntaD:'... En 1302, después de intensas luchas civiles, Dante fue condenado al exilio, al igual que otras 600 personas, y se le negó toda participación política. El Poeta llegó en el 1318 a Rávena, donde escribió el Paraíso, siendo acompañado por su amada Beatriz –al Infierno y Purgatorio lo acompañó su maestro Virgilio–. Fue enterrado en la iglesia de San Francisco de Asís, mientras Florencia soñó siempre con su regreso, hasta el punto de construirle una tumba en cuyo frente se lee: «Onorate al’altissimo poeta» (Honrad al más alto poeta). Pregunta: ¿Dante Alighieri fue político y…?', 
opcionD1:'maestro', opcionD2:'poeta', opcionD3:'médico', respuestaD:'poeta', 
preguntaE:'Desde el siglo 15 los florentinos han reclamado el retorno del cadáver de su más ilustre antepasado, pero se toparon con los frailes franciscanos, que custodiaban su tumba y lo consideraban como uno más de su comunidad. En 1519, el entonces papa León Décimo, florentino de nacimiento, autorizó la petición de la Academia Medicea de Florencia para __________ los restos mortales de Dante y transferirlos a su ciudad natal. Miguel Ángel Buonarroti, que estaba entre los firmantes, prometió erigir una sepultura digna del poeta.', 
opcionE1:'iluminar', opcionE2:'olvidar', opcionE3:'recuperar', respuestaE:'recuperar', 
preguntaF:'Pero cuando los delegados de la Academia abrieron la tumba, no había nada y se marcharon con las manos vacías. Luego se descubrió que habían sido los frailes franciscanos los que habían hecho “desaparecer” los huesos del Poeta. Con celo los frailes lo conservaron en el interior de su convento. En 1810, por causa de las leyes napoleónicas, los franciscanos tuvieron que dejar el convento y escondieron los restos. Casualmente aparecieron en 1865 y fueron trasladados al mausoleo que hoy conocemos como la tumba de Dante. Hoy en Florencia esperan que vuelva. Pregunta: ¿Qué pasó con los huesos de Dante Alighieri en 1865?', 
opcionF1:'aparecieron', opcionF2:'se perdieron', opcionF3:'los escondieron', respuestaF:'aparecieron',
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de GÓMEZ, Á. (1 de agosto 2019). Dante volverá a Florencia después de un exilio de 700 años. ABC Cultura. https://www.abc.es/cultura/abci-dante-volvera-florencia-despues-exilio-700-anos-201908010126_noticia.html',
pubTest:''
},


{nivel:'avanzado', testID:7, testname:'Canarios en la mina', instruccion:'',
preguntaA:'Desde el siglo 18 los mineros alemanes que trabajaban en las montañas del Harz, en la cordillera del Jura, encontraron en los canarios unos aliados para advertirles de los temidos escapes de gas grisú en las galerías de las minas.  Pregunta: ¿Qué eran los canarios para los mineros alemanes?',
opcionA1:'eran solo mascotas', opcionA2:'eran sus enemigos',opcionA3:'eran unos aliados',respuestaA:'eran unos aliados', 
preguntaB:'Todos los canarios domésticos que se crían en el mundo descienden de los canarios silvestres de las Islas Canarias, que fueron importados a Europa Continental por los españoles desde hace más de quinientos años. Iniciaron estas exportaciones admirados por la belleza del canto de esos pequeños pájaros que se mantenían como domésticos desde tiempos ancestrales. Pregunta: ¿Por qué fueron importados los canarios en toda Europa Continental?', 
opcionB1:'por la belleza de su canto', opcionB2:'porque eran mascotas tradicionales', opcionB3:'por la capacidad de detectar escapes de gas', respuestaB:'por la belleza de su canto', 
preguntaC:'En Alemania, en la ciudad de San Andreasberg, en plenas montañas del Harz, zona de importante extracción de carbón, las familias de los mineros seleccionaban unos canarios muy especiales, a los que se comenzó a llamar "Roller", por los sonidos graves y profundos que emitían, un tipo de canto completamente diferente al de los canarios ancestrales. Pregunta: ¿Qué característica tenían los canarios de la especie “Roller”?', 
opcionC1:'eran diestros en extraer carbón', opcionC2:'eran autóctonos de las montañas del Harz', opcionC3:'emitían sonidos graves y profundos', respuestaC:'emitían sonidos graves y profundos',
preguntaD:'Cuando los mineros del Harz bajaban a las galerías de la mina era frecuente que llevaran con ellos a alguno de sus canarios, cuya jaulita se colgaba de una viga iluminada de manera que el pájaro se viera incitado a cantar. La música del bosque conquistaba este ambiente inhóspito, pero no sólo para alegrar la dureza del trabajo, sino para advertir en caso de que se produjeran emanaciones del temido gas grisú. Pregunta: ¿Por qué ponían la jaula del canario al lado de la luz?', 
opcionD1:'para que el canario cantara',opcionD2:'para que el canario viera a los mineros', opcionD3:'para que el canario no se asustara', respuestaD:'para que el canario cantara', 
preguntaE:'El gas grisú produce la llamada "muerte dulce" al combinarse con la hemoglobina sanguínea para hacerla incapaz de liberar el oxígeno en los tejidos. Si los pájaros enmudecían, se mostraban tristes o alguno daba signos de muerte inminente, los mineros escapaban a toda velocidad, pero nunca olvidaban salvar al cantor que les había advertido del peligro.  Pregunta: ¿Por qué era peligroso el gas grisú?', 
opcionE1:'porque hacía que los canarios dejaran de cantar', opcionE2:'porque inhibía la liberación de oxígeno en los tejidos y causaba la muerte', opcionE3:'porque hacía que los mineros no pudieran correr',  respuestaE:'porque inhibía la liberación de oxígeno en los tejidos y causaba la muerte', 
preguntaF:'Los canarios no se utilizan hoy en día, en la actualidad hay detectores de gases, sistemas de ventilación, etc… el uso del canario se fue eliminando de las minas a partir de 1986. Pregunta: ¿Por qué hoy se siguen utilizando los canarios en las minas?',
opcionF1:'No, hoy no se están utilizando canarios en la mina', opcionF2:'porque los detectores de gas son menos efectivos', opcionF3:'porque los mineros prefieren los canarios', respuestaF:'No, hoy no se están utilizando canarios en la mina', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de DEL PINO, M. (3 de noviembre de 2013). Canarios en la mina: un seguro de vida. Libertad Digital.com. https://www.libertaddigital.com/opinion/2013-11-03/miguel-del-pino-canarios-en-la-mina-un-seguro-de-vida-6436421/',
pubTest:''
},

{nivel:'avanzado', testID:8, testname:'Principio de la navaja de Ockham', instruccion:'',
preguntaA:'La teoría filosófica de la navaja de Ockham dice que, ante varias posibles explicaciones para un fenómeno o un hecho, la más simple es la correcta. A esta teoría se la conoce también como principio de parsimonia o principio de economía. Muchos científicos argumentan que la teoría de la navaja de Ockham no es una teoría científica, puesto que la simpleza o complejidad de una explicación es un juicio subjetivo. Por tal motivo, ante dos explicaciones para un fenómeno, distintas personas pueden tener opiniones diferentes sobre cuál es la más simple. Pregunta: ¿Por qué los científicos consideran que esta teoría no es científica?',
opcionA1:'porque Ockham era un filósofo y no científico', opcionA2:'porque \“simpleza\” o \“complejidad\” son juicios subjetivos',opcionA3:'todas las anteriores',respuestaA:'porque \“simpleza\” o \“complejidad\” son juicios subjetivos', 
preguntaB:'Ockham no es el inventor del principio de simplicidad o de parsimonia que asegura que las explicaciones más simples tienden a ser las correctas. Sus inventores fueron Aristóteles, Tomás de Aquino y otros filósofos que Ockham leía. Tampoco usó la palabra “navaja” para referirse a este principio. La primera aparición que se conoce del término \“navaja de Ockham\” data del año 1852, en el trabajo del matemático británico William Rowan Hamilton. Ockham nunca intentó demostrar la validez del principio que lleva el nombre de su navaja. Pero lo usó de forma innovadora, y eso logró que se lo asociara con él. Pregunta: ¿Por qué este principio está asociado al nombre de Ockham?', 
opcionB1:'porque Ockham trabajó con el matemático William Rowan Hamilton', opcionB2:'porque Ockham utilizó el principio de forma innovadora', opcionB3:'porque Ockham leía a Tomás de Aquino y Aristóteles', respuestaB:'porque Ockham utilizó el principio de forma innovadora', 
preguntaC:'Para Ockham, el principio de simplicidad limita la multiplicación de teorías. El filósofo fomentaba la siguiente formulación del principio: “es inútil hacer con más lo que puede hacerse con menos”. Con este postulado, Ockham aseguraba que las teorías están pensadas para hacer cosas tales como explicar y predecir, y esas cosas pueden llevarse a cabo más efectivamente con una menor cantidad de variables. En cierto punto, esto es simple sentido común. A modo de ejemplo, supongamos que vamos en auto y éste repentinamente detiene su marcha. El medidor de combustible indica que el tanque está vacío. Sería innecesario suponer que, además de que se agotó la gasolina, el auto también puede haberse quedado sin aceite. Sólo se necesita una hipótesis para explicar lo sucedido con el auto. Pregunta: ¿Según el principio de simplicidad, por qué el auto se detuvo?', 
opcionC1:'porque se agotó el aceite', opcionC2:'porque se agotó la gasolina', opcionC3:'porque se agotaron la gasolina y el aceite', respuestaC:'porque se agotó la gasolina',
preguntaD:'¿Para qué sirve la teoría de la navaja de Ockham? Así como una navaja real se usa para recortar el pelo o la barba, eliminando los excesos, de la misma forma la navaja de Ockham recorta las hipótesis innecesarias en una teoría científica. De esta forma se procura llegar siempre a la explicación más simple. En conclusión, la navaja de Ockham otorga prioridad a la simplicidad con miras a reducir los riesgos de error. Cada hipótesis conlleva la posibilidad de estar equivocada. Entonces, cuantas más hipótesis se acepten, mayor será el riesgo de incurrir en una equivocación. Ockham se esforzó por evitar el error a toda costa, aún si eso significaba abandonar creencias establecidas. Esta forma de pensar le ganó la reputación de destructor de la síntesis medieval de fe y la razón. Pregunta: ¿Qué buscaba Ockham con el principio?', 
opcionD1:'destruir la síntesis medieval de la fe y la razón',opcionD2:'abandonar todas las creencias establecidas', opcionD3:'reducir los riesgos de error, minimizando el número de hipótesis', respuestaD:'reducir los riesgos de error, minimizando el número de hipótesis', 
preguntaE:'En el área de la investigación policial se aplica la teoría de la navaja de Ockham para llegar lo más rápidamente posible al esclarecimiento de un crimen o delito. En el blog Mundo Criminal explican cómo los investigadores de homicidios aplican el principio de simplicidad para acelerar la resolución de los casos. \“Alrededor del 97 por ciento de los homicidios están motivados por dinero, sexo o motivos pasionales (riñas, peleas, discusiones acaloradas, etc), y los investigadores lo saben\”, señalan en el blog. \“De igual forma, saben que los autores de homicidios o desapariciones sospechosas se encuentran en el entorno de la víctima. En ese entorno es donde empiezan a investigar\”. Pregunta: En el caso policial descrito, según la navaja de Ockham, ¿qué se debe investigar primero?', 
opcionE1:'investigar sólo el entorno del área', opcionE2:'investigar primero el entorno de la víctima', opcionE3:'investigar el 97 por ciento de los homicidios',  respuestaE:'investigar primero el entorno de la víctima', 
preguntaF:'En medicina se aplica ampliamente el principio de la navaja de Ockham para maximizar la precisión de los diagnósticos. El médico Arnoldo Kraus escribió una nota sobre ética médica en la que enfatiza que la navaja de Ockham es indispensable. \“En medicina, tal y como lo enseñaron los viejos clínicos, quienes conocían a fondo al paciente, es mejor un diagnóstico para explicar la enfermedad en vez de dos\”, señala el doctor Kraus. Pregunta: ¿Qué opina el médico Arnoldo Kraus sobre la navaja de Ockham?',
opcionF1:'es afilada', opcionF2:'es obsoleta', opcionF3:'es indispensable', respuestaF:'es indispensable', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de PUROSCUENTOS.BLOG (21 de noviembre de 2019). Teoría de la navaja de Occam. Su origen y ejemplos. Puroscuentos.blog. https://puroscuentos.blog/teoria-de-la-navaja-de-ockham-su-origen-y-ejemplos/',
pubTest:''
},

{nivel:'avanzado', testID:9, testname:'La promesa del rey Felipe II a Dios', instruccion:'',
preguntaA:'Aunque no siempre está a la vista, en las colecciones permanentes del Museo Nacional de Historia Estadounidense del Smithsonian en Washington, ____________ un monje.',
opcionA1:'ahí', opcionA2:'hay',opcionA3:'están',respuestaA:'hay', 
preguntaB:'El monje camina trazando un trapezoide, mientras se golpea el pecho con el brazo derecho, y levanta y baja una pequeña cruz de madera y un rosario que lleva en la mano izquierda. Su cabeza gira y asiente, sus ojos se mueven y, silenciosamente, pronuncia oraciones. De vez en cuando, se lleva la cruz a los labios y la besa. Pregunta: ¿Qué hace el monje?', 
opcionB1:'Golpea su pecho con el brazo derecho', opcionB2:'Besa una cruz con sus labios', opcionB3:'Todas las anteriores', respuestaB:'Todas las anteriores', 
preguntaC:'Le llaman \"el autómata de un monje\", se sabe que fue hecho en el siglo 16 (XVI) y que llegó a la capital de EE. UU. desde Ginebra en 1977. Se sabe también que está hecho de madera y hierro, que tiene rastros de esmalte de distintos colores, que mide 40,64 cm x 12,7 cm x 15,24 cm y que se mueve - todavía, después de más de 4 siglos - impulsado por un mecanismo de reloj de cuerda que está escondido en su cuerpo. Pregunta: ¿Por qué se mueve el monje?', 
opcionC1:'por un mecanismo de relojería', opcionC2:'de madera y hierro', opcionC3:'por rastros de esmalte', respuestaC:'por un mecanismo de relojería',
preguntaD:'Este monje se distingue por estar asociado a una leyenda. En 1562, Carlos de Austria y príncipe de Asturias, el hijo del rey Felipe II de España y su primera esposa, la infanta María Manuela de Portugal, estaba en el palacio real y al bajar unas escaleras, tropezó, cayó y se golpeó la cabeza contra una puerta. Al principio no parecía que fuera grave, pues seguía consciente. Pero, pronto, se le hinchó la cabeza de manera alarmante, le dio fiebre, empezó a delirar y perdió la vista. En cualquier caso, esta sería una calamidad, pero en este caso, agravada por el hecho de que el joven estaba destinado a ser rey. Pregunta: ¿Por qué hubiese sido una calamidad que Carlos de Austria muriese en ese accidente?', 
opcionD1:'Porque había perdido la vista',opcionD2:'Porque era el heredero de la corona', opcionD3:'Porque el rey tendría que ir a la guerra contra Portugal', respuestaD:'Porque era el heredero de la corona', 
preguntaE:'El príncipe heredero estaba agonizando. El rey ya no sabía qué más podía hacer. Era uno de los dueños del mundo: gobernaba sobre casi toda la recién descubierta América, así como gran parte de Europa; las Filipinas, al otro lado del mundo, habían sido nombradas en su honor; era amigo del Papa... pero su ___________ no le alcanzaba para salvar a su hijo. Así que recurrió a Dios. La leyenda dice que se arrodilló junto a su hijo en el lecho de muerte e hizo un pacto con Dios: si hacía el milagro de sanar a su hijo, él lo pagaría con un milagro para Dios.', 
opcionE1:'pasado', opcionE2:'poder', opcionE3:'idea',  respuestaE:'poder', 
preguntaF:'En cuestión de una semana, Carlos de Austria se recuperó y sanó. Hay documentos que cuentan que apenas pudo hablar, el príncipe Carlos le relató a su padre un sueño que había tenido mientras estaba mal. En él, un monje maravilloso, con la cabeza rapada, la nariz puntiaguda, mirada penetrante y vestido con los hábitos franciscanos, había entrado en sus aposentos, se había acercado a su lecho de muerte y, con la cruz en la mano, le había dicho que todo iba a estar bien... y fue entonces cuando se mejoró. Pregunta: ¿Qué le dijo el príncipe a su padre?',
opcionF1:'que un monje de largos cabellos entró a sus aposentos', opcionF2:'que un monje le dijo que todo iba a estar bien', opcionF3:'todas las anteriores', respuestaF:'que un monje le dijo que todo iba a estar bien', 
preguntaG:'Gracias a la descripción no había duda de que se trataba de fray Diego de Alcalá, cuyos restos habían sido puestos a los pies de la cama dónde yacía el príncipe. Este sueño le dio una idea al rey para pagar su cuenta pendiente con Dios, entonces citó a uno de los mejores relojeros de Europa, un italo-español llamado Juanelo Turriano, y le pidió -de la manera que piden los monarcas- que hiciera una versión mecánica de Diego de Alcalá. Y así fue creado ese monje que todavía hoy se mueve poniendo un pie tras el otro al _____________, se da golpes de pecho pareciendo cantar el mea culpa, y reza, como lo ha venido haciendo desde hace 400 años.', 
opcionG1:'pensar', opcionG2:'saltar', opcionG3:'caminar', respuestaG:'caminar', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de VENTURA, D. (3 de noviembre de 2019). La maravilla mecánica con la que el todopoderoso rey Felipe II le cumplió una promesa a Dios. BBC News Mundo. https://www.bbc.com/mundo/noticias-50252221',
pubTest:''
},

{nivel:'avanzado', testID:10, testname:'Las frases que nadie dijo', instruccion:'',
preguntaA:'Tras la caída del Muro de Berlín el 10 de noviembre de 1989, algunos políticos pensaron que la unificación de Alemania volvía a resucitar el fantasma de la Segunda Guerra Mundial. Otros temieron que iba a costarle mucho dinero a la Unión Europea. En aquellos momentos de incertidumbre prosperó una frase que decía: «Me gusta tanto Alemania que prefiero que haya dos». La sentencia ha sido atribuida al presidente francés Françoise Mitterrand, al siete veces primer ministro italiano Giulio Andreotti y al premio Nobel francés Françoise Mauriac, que falleció años antes de la desaparición de la República Democrática Alemana. Pregunta: ¿Cuándo se reunificó Alemania?',
opcionA1:'El 10 de noviembre de 1989', opcionA2:'El año que falleció Françoise Mauriac',opcionA3:'Antes de la caída del muro de Berlín',respuestaA:'El 10 de noviembre de 1989', 
preguntaB:'A estas citas de múltiple paternidad se suman otras que nunca fueron dichas por sus supuestos autores. Entre ellas, hay una muy famosa que se adjudica a Maquiavelo: «El fin justifica los medios». Lo que realmente escribió el filósofo y diplomático florentino en su obra El príncipe fue lo siguiente: «Si el monarca lleva cuidado de conservar el Estado, los medios serán siempre estimados, honorables y aplaudidos por todo el mundo». Pregunta: ¿Quién fue Maquiavelo?', 
opcionB1:'El autor de El Príncipe', opcionB2:'Un filósofo y diplomático', opcionB3:'Todas las anteriores', respuestaB:'Todas las anteriores', 
preguntaC:'En 1633, la Inquisición acusó a Galileo Galilei de defender la teoría de Copérnico de que la Tierra era la que se movía alrededor del Sol. Y siempre se afirmó que tras oír su condena Galileo murmuró: «¡Eppur si muove!» (\“Y, sin embargo, se mueve\”). Lo cierto es que un comentario como ese, aun cuando fuese un murmullo apenas audible, le habría costado la cabeza al matemático italiano. Pregunta: ¿Qué condenaba la inquisición?', 
opcionC1:'La teoría que la tierra era el centro del universo', opcionC2:'La teoría que la tierra se movía alrededor del sol', opcionC3:'La teoría que la tierra no se movía', respuestaC:'La teoría que la tierra se movía alrededor del sol',
preguntaD:'Tampoco es de Voltaire una sentencia que siempre se le atribuye: «No estoy de acuerdo con lo que dices, pero defenderé hasta la muerte tu derecho a decirlo». La cita fue utilizada por primera vez por Evelyn Beatrice Hall, que escribió un libro titulado Los amigos de Voltaire (1906). Pregunta: ¿Qué ocurrió en el año 1906?', 
opcionD1:'Murió Voltaire',opcionD2:'Voltaire escribió un libro', opcionD3:'Se escribió un libro sobre Voltaire', respuestaD:'Se escribió un libro sobre Voltaire', 
preguntaE:'Las diferencias ideológicas constituyen otro factor que favorece la falsa adjudicación de citas históricas. «Cuando oigo la palabra ‘cultura’, saco mi revólver», es una frase que los anglosajones han atribuido a los dirigentes nazis Hermann Göring y Joseph Goebbels. En España, la misma sentencia, con pequeñas variaciones, se ha adjudicado a los generales Emilio Mola y Millán Astray. En realidad, la frase dice así: «Cuando oigo la palabra ‘cultura’, ¡le quito el seguro a mi Browning!», y su origen es la obra teatral Schlageter, escrita por Haans Johst, un poeta y dramaturgo nazi que le dedicó esta obra teatral a Hitler como regalo de cumpleaños. Pregunta: ¿Quién le hizo un regalo a Hitler? y, ¿Cuál fue el regalo?', 
opcionE1:'Goebbels. Regaló su revolver', opcionE2:'Haans Johst. Regaló una Browning', opcionE3:'Ninguna de las anteriores',  respuestaE:'Ninguna de las anteriores', 
preguntaF:'En la literatura también aparecen algunas citas falsas. Por ejemplo, Sherlock Holmes, el genial detective ideado por Arthur Conan Doyle, jamás pronunció la famosa frase: “Elemental, mi querido Watson”. Pregunta: ¿Quién fue Sherlock Holmes?',
opcionF1:'Un amigo de Arthur Conan Doyle', opcionF2:'Un detective ideado por Watson', opcionF3:'Un personaje de ficción', respuestaF:'Un personaje de ficción', 
preguntaG:'“Se puede engañar a todo el mundo alguna vez, y a algunas personas todo el tiempo, pero no se puede engañar a todo el mundo todo el tiempo”. La frase se atribuye a Abraham Lincoln, pero no está en ningún periódico ni documento de la época. Según esta frase, ¿A quién se puede engañar?', 
opcionG1:'A todo el mundo, siempre', opcionG2:'A nadie, nunca', opcionG3:'A todo el mundo, a veces', respuestaG:'A todo el mundo, a veces', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'extracto artículo de SEGOVIA, J.(15 de febrero de 2017). Las frases que nadie dijo y todos repiten. XLSemanal. https://www.xlsemanal.com/conocer/20170215/las-frases-que-nadie-dijo-y-todos-repiten.html',
pubTest:''
},



];