import { Testbase } from './testbase';

export const BASEPARATESTSPT2: Testbase[] = [


{nivel:'intermedioPT', testID:1, testname:'VERBOS-Presente e Infinitivo 1', instruccion:'Seleccione a conjugação correcta no presente do indicativo (Select the right conjugation)',
preguntaA:'A borboleta-monarca, típica da América do Norte, _________ nas suas antenas uma espécie de "relógio" de vinte e quatro (24) horas ( verbo CARREGAR)', 
opcionA1:'carrego', opcionA2:'carrega', opcionA3:'carregam', respuestaA:'carrega', 
preguntaB:'que a _______ a _______ os quatro mil (4.000) quilómetros  ( verbos AJUDAR e NAVEGAR)',
opcionB1:'ajuda a navegar', opcionB2:'ajudamos a navegar', opcionB3:'ajuda a navegam', respuestaB:'ajuda a navegar', 
preguntaC:'que ________ no inverno até ao México ( verbo PERCORRER)',
opcionC1:'percorro', opcionC2:'percorrerei', opcionC3:'percorre', respuestaC:'percorre', 
preguntaD:'Todos os Outonos, cerca de cem (100) milhões de borboletas-monarca _______ para sul ( verbo MIGRAR)', 
opcionD1:'migram', opcionD2:'migrei', opcionD3:'migra', respuestaD:'migram', 
preguntaE:' _________ de acordo com a posição do sol,  ( verbo NAVEGAR)', 
opcionE1:'Navegamos', opcionE2:'Navegou', opcionE3:'Navegam', respuestaE:'Navegam', 
preguntaF:'ajustando os seus cálculos à medida que este se ________ no céu.  ( verbo DESLOCAR)', 
opcionF1:'desloca', opcionF2:'deslocam', opcionF3:'deslocar', respuestaF:'desloca',
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'excerto de um texto traduzido de BURNS, J. (25 de septiembre de 2009). El GPS de las mariposas monarca. BBC News Mundo. https://www.bbc.com/mundo/ciencia-tecnologia/2009/09/090924-1700-mariposa-monarca_gtg',
pubTest:''
},

{nivel:'intermedioPT', testID:2, testname:'VERBOS-Presente e Infinitivo 2', instruccion:'Seleccione a conjugação correcta no presente do indicativo (Select the right conjugation)',
preguntaA:'Os beija-flores _______  ______ de um lado para o outro, para trás e até pairar num só ponto.( verbos PODER y VOAR Presente e Infinitivo) ', 
opcionA1:'podes voar', opcionA2:'podem voar',opcionA3:'podem voam',respuestaA:'podem voar', 
preguntaB:'No mundo das aves, os beija-flores _____ o recorde do bater de asas mais rápido,( verbo TER )', 
opcionB1:'têm', opcionB2:'ter', opcionB3:'tem', respuestaB:'têm', 
preguntaC:'os beija-flores _______ as asas 40-50 vezes por segundo e algumas espécies até 80 vezes. ( verbo BATER )', 
opcionC1:'bates', opcionC2:'bato', opcionC3:'batem', respuestaC:'batem',
preguntaD:'O truque para voar como um beija-flor ______ em ser a ave mais pequena de todas, ( verbo ESTAR )', 
opcionD1:'estou',opcionD2:'estão', opcionD3:'está', respuestaD:'está', 
preguntaE:'bem como a ave que _______ as asas mais rapidamente.( verbo BATER )', 
opcionE1:'bate', opcionE2:'batem', opcionE3:'batemos',  respuestaE:'bate', 
preguntaF:'Os beija-flores __________ diariamente o seu peso corporal em néctar para complementar a sua energia corporal.(  verbos CONSOMIR )', 
opcionF1:'consomo', opcionF2:'consomem', opcionF3:'consomir', respuestaF:'consomem', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'excerto de um texto traduzido de CUSÓ,Ò.(21 de noviembre de 2022).Desvelando los secretos del vuelo de los colibríes en súper \'slow motion\'. NATIONAL GEOGRAPHIC España. https://www.nationalgeographic.com.es/naturaleza/desvelando-vuelo-colibries-super-slow-motion-15701',
pubTest:''
},

{nivel:'intermedioPT', testID:3, testname:'VERBOS-Pretérito (Perfeito e Imperfeito) 1', instruccion:'Seleccione a conjugação correcta (Select the right conjugation)',
preguntaA:'Alguns dos estudos de observação realizados há 50 anos indicavam que, quando as antenas das borboletas ______ retiradas,  ( verbos SER-Pretérito Imperfeito)', 
opcionA1:'era', opcionA2:'eram',opcionA3:'eras',respuestaA:'eram', 
preguntaB:'as borboletas _________ de _____ na direção certa.  ( verbos DEIXAR e VOAR -Pretérito Imperfeito)', 
opcionB1:'deixava de voaram', opcionB2:'deixavam de voar', opcionB3:'deixavam de voaram', respuestaB:'deixavam de voar', 
preguntaC:'Os especialistas retiraram as antenas de um grupo de borboletas e __________ ( verbo COMPARAR-Pretérito Perfeito)', 
opcionC1:'compararam', opcionC2:'comparou', opcionC3:'comparei', respuestaC:'compararam',
preguntaD:'a forma como ________ com a de um grupo controlado num simulador de voo ( verbo VOAR-Pretérito Imperfeito)', 
opcionD1:'voávamos',opcionD2:'voava', opcionD3:'voavam', respuestaD:'voavam', 
preguntaE:'Todas as borboletas intactas _______ para sudoeste, como fazem normalmente, ( verbo VOAR-Pretérito Perfeito)', 
opcionE1:'voaste', opcionE2:'voaram', opcionE3:'volei',  respuestaE:'voaram', 
preguntaF:'mas as borboletas sem antenas, embora também voassem, o _________ em direcções diferentes. ( verbo FAZER-Pretérito Perfeito)', 
opcionF1:'fizeram', opcionF2:'fiz', opcionF3:'fez', respuestaF:'fizeram', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'excerto de um texto traduzido de BURNS, J. (25 de septiembre de 2009). El GPS de las mariposas monarca. BBC News Mundo. https://www.bbc.com/mundo/ciencia-tecnologia/2009/09/090924-1700-mariposa-monarca_gtg',
pubTest:''
},

{nivel:'intermedioPT', testID:4, testname:'VERBOS-Pretérito (Perfeito e Imperfeito) 2', instruccion:'Seleccione a conjugação correcta (Select the right conjugation)',
preguntaA:'O imperador Júlio César, há quase 2.000 anos, _______ um calendário muito semelhante ao que utilizamos atualmente. ( verbo IMPOR Pretérito Perfeito) ', 
opcionA1:'impuseram', opcionA2:'impôs',opcionA3:'impus',respuestaA:'impôs', 
preguntaB:'O chamado calendário juliano _________ os 12 meses com 30 e 31 dias, começando o ano em março, por ser o início da primavera.  ( verbo ALTERNAR Pretérito Imperfeito )', 
opcionB1:'alternava', opcionB2:'alternavas', opcionB3:'alternavam', respuestaB:'alternava', 
preguntaC:'O calendário juliano ________ durante séculos, mas não é exato porque o ano solar é, na verdade, um pouco mais curto: 11 minutos e 14,784 segundos. ( verbo SERVIR Pretérito Perfeito) ', 
opcionC1:'serviu', opcionC2:'serviste', opcionC3:'serviram', respuestaC:'serviu',
preguntaD:'Para corrigir a discrepância, o Papa Gregório XIII _________ com o seu calendário gregoriano em 1582. ( verbo INTERVIR Pretérito Perfeito )', 
opcionD1:'intervieste',opcionD2:'interveio', opcionD3:'intervim', respuestaD:'interveio', 
preguntaE:'Para estabelecer o calendário, os governantes do ano de 1582 _________, em vez de eliminar os anos bissextos nas quatro décadas seguintes, ( verbo DECIDIR Pretérito Perfeito)', 
opcionE1:'decidi', opcionE2:'decidiu', opcionE3:'decidiram',  respuestaE:'decidiram', 
preguntaF:'eles _________ 10 dias e _________ de quinta-feira, 5 de outubro, para sexta-feira, 14 de outubro de 1582. (  verbos CORTAR y SALTAR Pretérito Perfeito )', 
opcionF1:'cortaram - saltaram', opcionF2:'cortei - saltei', opcionF3:'cortaste - saltaste', respuestaF:'cortaram - saltaram', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'excerto de um texto traduzido de BBC.(28 de febrero de 2020). 30 de febrero, el día que solo existió una vez en la historia. Semana.com. https://www.semana.com/vida-moderna/articulo/30-de-febrero-el-dia-que-solo-existio-una-vez-en-la-historia/654452/',
pubTest:''
},

{nivel:'intermedioPT', testID:5, testname:'VERBOS-Pretérito (Perfeito e Imperfeito) 3', instruccion:'Seleccione a conjugação correcta (Select the right conjugation)',
preguntaA:'Em 1946, o crocodilo Saturno ________ a viver no jardim zoológico de Moscovo. ( verbo CHEGAR Pretérito Perfeito) ', 
opcionA1:'chegou', opcionA2:'cheguei',opcionA3:'chegaram',respuestaA:'chegou', 
preguntaB:'E _____ um acontecimento e tanto, porque nessa altura só havia dois crocodilos na capital soviética. ( verbo SER Pretérito Perfeito )', 
opcionB1:'ser', opcionB2:'fui', opcionB3:'foi', respuestaB:'foi', 
preguntaC:'Saturno _________ ________ (verbos GOSTAR e DORMIR - Pretérito Imperfeito) ', 
opcionC1:'gostou de dormia', opcionC2:'gostava de dormir', opcionC3:'gostava de dormia', respuestaC:'gostava de dormir',
preguntaD:'e não ____ muito exigente com a ementa, gostava de comer peixe, coelhos e roedores. (verbo SER Pretérito Imperfeito )', 
opcionD1:'eras',opcionD2:'eram', opcionD3:'era', respuestaD:'era', 
preguntaE:'Saturno era muito calmo, quase não ________ distúrbios. ( verbo CAUSAR Pretérito Imperfeito)', 
opcionE1:'causava', opcionE2:'causei', opcionE3:'causavas',  respuestaE:'causava', 
preguntaF:'Em 2020, o Jardim Zoológico de Moscovo __________ a morte de Saturno. (  verbos COMUNICAR Pretérito Perfeito )', 
opcionF1:'comuniquei', opcionF2:'comunicou', opcionF3:'comunicaram', respuestaF:'comunicou', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'excerto de um texto traduzido de COLÁS, X.(24 de mayo de 2020). Muere \'Saturno\', el cocodrilo que conoció a Hitler y escapó durante los bombardeos de Berlín. https://www.elmundo.es/ciencia-y-salud/ciencia/2020/05/23/5ec9759221efa0f26a8b4638.html',
pubTest:''
},

{nivel:'intermedioPT', testID:6, testname:'Pronomes reflexivos e adjectivos possessivos', instruccion:'Selecionar os pronomes e adjectivos correctos (Select the right options)',
preguntaA:'Eu dou- ____ bem com (my) _____ pai porque temos o mesmo sentido de humor.', 
opcionA1:'te   -    o meu', opcionA2:'me   -    o meu',opcionA3:'me   -    o teu',respuestaA:'me   -    o meu', 
preguntaB:'Ela dá- ____ bem com (her) ______ pai porque eles têm o mesmo sentido de humor.', 
opcionB1:'me   -    o seu', opcionB2:'se   -    os seus', opcionB3:'se   -    o seu', respuestaB:'se   -    o seu', 
preguntaC:'Eles não ____ dão bem com (their) _______ pais', 
opcionC1:'se   -   os seus', opcionC2:'ses   -   os seus', opcionC3:'se   -   os teus', respuestaC:'se   -   os seus',
preguntaD:'Eles não ____ dão bem com (their) _____ pai', 
opcionD1:'se   -    o seus',opcionD2:'se   -    o seu', opcionD3:'ses   -    o seu', respuestaD:'se   -    o seu', 
preguntaE:'Com quem é que tu ____ dás melhor?. Com ____ (your) pai o com ___ (your) mãe', 
opcionE1:'te  -  o teu   -  o seu', opcionE2:'se  -  o seu   -  a sua', opcionE3:'te  -  o teu   -  a tua',  respuestaE:'te  -  o teu   -  a tua', 
preguntaF:'Todos eles ____ dão muito mal com (their) ______ professor', 
opcionF1:'se   -    o seu', opcionF2:'se   -    o seus', opcionF3:'ses   -    o seu', respuestaF:'se   -    o seu', 
preguntaG:'', opcionG1:'', opcionG2:'', opcionG3:'', respuestaG:'', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},

{nivel:'intermedioPT', testID:7, testname:'VERBOS Futuro do Presente ', instruccion:'Seleccione a conjugação correcta no tempo verbal Futuro do Presente (Select the right conjugation)',
preguntaA:'No próximo ano, eu __________ (verbo ESTUDAR) no exterior', 
opcionA1:'estudarei', opcionA2:'estudarás',opcionA3:'estudei',respuestaA:'estudarei', 
preguntaB:'Ela se __________ (verbo MAQUILHAR) para ir à festa', 
opcionB1:'maquilharão', opcionB2:'maquilhará', opcionB3:'maquilharás', respuestaB:'maquilhará', 
preguntaC:'Daqui a cinco anos, eu _______ (verbo SER) uma profissional bem-sucedida', 
opcionC1:'serás', opcionC2:'seremos', opcionC3:'serei', respuestaC:'serei',
preguntaD:'Na próxima semana, ________ (verbo FAZER) uma festa de aniversário', 
opcionD1:'fareis',opcionD2:'faremos', opcionD3:'farás', respuestaD:'faremos', 
preguntaE:'Em breve, nós ____________ (verbo COMEÇAR) a construção do projeto', 
opcionE1:'começará', opcionE2:'começarão', opcionE3:'começaremos',  respuestaE:'começaremos', 
preguntaF:'No próximo mês, eu _______ (verbo FAZER) uma dieta mais saudável', 
opcionF1:'fareis', opcionF2:'farei', opcionF3:'farão', respuestaF:'farei', 
preguntaG:'Tu ____________ (verbo SURPREENDER) toda a gente na festa', 
opcionG1:'surpreenderás', opcionG2:'surpreendeste', opcionG3:'surpreenderá', respuestaG:'surpreenderás', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},

{nivel:'intermedioPT', testID:8, testname:'Verbo IR + Infinitivo', instruccion:'Substituir o verbo no futuro pela expressão IR + infinitivo (Select the right conjugation)',
preguntaA:'No próximo ano, estudarei no exterior', 
opcionA1:'vou estudarei', opcionA2:'vamos estudar',opcionA3:'vou estudar',respuestaA:'vou estudar', 
preguntaB:'Ela se maquilhará para ir à festa', 
opcionB1:'vamos maquilhar-se', opcionB2:'vai maquilhar-se', opcionB3:'vou maquilhar-se', respuestaB:'vai maquilhar-se', 
preguntaC:'Daqui a cinco anos, serei uma profissional bem-sucedida', 
opcionC1:'vou ser', opcionC2:'vão ser', opcionC3:'vou serei', respuestaC:'vou ser',
preguntaD:'Na próxima semana, faremos uma festa de aniversário', 
opcionD1:'vais fazer',opcionD2:'vamos fazer', opcionD3:'vão fazer', respuestaD:'vamos fazer', 
preguntaE:'Em breve, começaremos a construção do projeto', 
opcionE1:'vamos começar', opcionE2:'vais começar', opcionE3:'vou começar',  respuestaE:'vamos começar', 
preguntaF:'No próximo mês, farei uma dieta mais saudável', 
opcionF1:'vou fazer', opcionF2:'vamos fazer', opcionF3:'vão fazer', respuestaF:'vou fazer', 
preguntaG:'Tu surpreenderás toda a gente na festa', 
opcionG1:'vai surpreender', opcionG2:'vamos surpreender', opcionG3:'vais surpreender', respuestaG:'vais surpreender', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},

{nivel:'intermedioPT', testID:9, testname:'Advérbios de lugar', instruccion:'A estação de comboios fica do lado direito do centro comercial. A universidade e o museu estão do lado esquerdo do centro comercial. O museu é um edifício muito pequeno diante da universidade. O aeroporto fica no outro extremo da cidade. O centro comercial tem um cinema no primeiro andar e uma loja de roupa no segundo andar, bem como um parque de estacionamento na cave.',
preguntaA:'A universidade fica _______ do museu', 
opcionA1:'por cima', opcionA2:'perto',opcionA3:'debaixo',respuestaA:'perto', 
preguntaB:'O aeroporto fica ________ da estação de comboios', 
opcionB1:'ao lado', opcionB2:'em frente', opcionB3:'longe', respuestaB:'longe', 
preguntaC:'O cinema fica _______ do centro comercial', 
opcionC1:'dentro', opcionC2:'fora', opcionC3:'entre', respuestaC:'dentro',
preguntaD:'A loja de roupa fica ________ do cinema', 
opcionD1:'longe',opcionD2:'diante', opcionD3:'por cima', respuestaD:'por cima', 
preguntaE:'O parque de estacionamento do centro comercial situa-se ________ do cinema', 
opcionE1:'em frente', opcionE2:'debaixo', opcionE3:'longe',  respuestaE:'debaixo', 
preguntaF:'O centro comercial está situado ________ a estação de comboios e a universidade.', 
opcionF1:'entre', opcionF2:'dentro', opcionF3:'por cima', respuestaF:'entre', 
preguntaG:'A universidade fica por _______ do museu', 
opcionG1:'detrás', opcionG2:'diante', opcionG3:'debaixo', respuestaG:'detrás', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},


{ nivel:'intermedioPT', testID:10, testname:'VERBOS Imperativo', instruccion:'Seleccione a opção correcta (Select the right option)',
preguntaA:'______ sua escolha com sabedoria (Você - FAZER)', 
opcionA1:'faz', opcionA2:'Faça',opcionA3:'façam',respuestaA:'Faça', 
preguntaB:'__________ às minhas perguntas com clareza (Tu - RESPONDER)', 
opcionB1:'Responde', opcionB2:'Responda', opcionB3:'respondam', respuestaB:'Responde', 
preguntaC:'Por favor, __________ uma história (Tu - CONTAR - a mim)', 
opcionC1:'conta-me', opcionC2:'contem-me', opcionC3:'conta-le', respuestaC:'conta-me',
preguntaD:'Não _______ isso, é perigoso! (Tu - FAZER)', 
opcionD1:'faças',opcionD2:'façam', opcionD3:'faça', respuestaD:'faças', 
preguntaE:'__________ cada momento da vida (Você - APROVEITAR)', 
opcionE1:'Aproveitem', opcionE2:'Aproveite', opcionE3:'Aproveitemos',  respuestaE:'Aproveite', 
preguntaF:'Não se _________ de trazer o seu documento (Você - ESQUECER)', 
opcionF1:'esqueça', opcionF2:'esqueçamos', opcionF3:'esqueças', respuestaF:'esqueça', 
preguntaG:'___________ como funciona esse processo (Você - EXPLICAR - a mim)', 
opcionG1:'Explicar-me', opcionG2:'Explica-me', opcionG3:'Explique-me', respuestaG:'Explique-me', 
preguntaH:'', opcionH1:'', opcionH2:'', opcionH3:'', respuestaH:'', 
preguntaI:'', opcionI1:'', opcionI2:'', opcionI3:'', respuestaI:'',
final:'',
pubTest:''
},



];

