
export const ENPALABRAS: string[] = [
'The basement',
'Grandfather',
'The library has a lot of books',
'The harp strings',
'He writes very good Portuguese',
'Storage room',
'Seasons of the year',
'It is not easy to get the right address',
'Where are my pencils?',
'What time do you leave work? (You-informal/omit subject pronoun)',
'The balcony',
'Regions',
'The shoes are very pretty',
'A dessert with strawberries and peaches',
'Close',
'Corridor',
'Family',
'The program is perfect',
'Plate with fork and knife',
'I drink water',
'The kitchen',
'Parts of the house',
'The plate is dirty',
'The antique cars',
'They(males) go to the mountains',
'Living room',
'December',
'Let\'s go to the beach this afternoon',
'A flight to Paris',
'the lady doesn\'t like to dance',
'Room',
'November',
'Age',
'It\'s raining',
'The horse is thirsty',
'The penguins don\'t fly',
'October',
'Date of birth',
'Love life',
'Spring, Summer, Fall, Winter',
'She draws a flower',
'September',
'Address',
'The clocks are synchronized',
'Cell phone number',
'She wears high heels ',
'August',
'Good evening',
'The soup is very cold',
'Goodbye, see you later',
'The spirals in the nature',
'July',
'Good afternoon',
'The candies are of mint',
'Hello',
'She likes to smile',
'June',
'Good morning',
'A tall building',
'The last working day of the week is Friday',
'there is only one swan in the lake',
'He likes to walk',
'May',
'Great-granddaughter ',
'I like to eat ice cream',
'First working day of the week is Monday',
'there are many pigeons in the square',
'The house is very big',
'April',
'Great-grandson ',
'Forests are the lungs of the planet',
'The days of the week',
'the cat is very fat',
'My plane leaves in a few minutes',
'March',
'Sister-in-law',
'A sunset on the beach',
'The Languages',
'the dog has no name',
'I like to paint (omit subject pronoun)',
'February',
'Brother-in-law',
'The students study for the exam',
'The countries and the cities',
'They(females) don\'t like to run',
'Don\'t forget to close (You - informal way)',
'January',
'Cousin (female)',
'They stay at home',
'The girls don\'t want to play',
'They(males) like to swim',
'She wears a pink ribbon',
'Sunday',
'Cousin (male)',
'She likes to sing',
'The clouds are in the sky',
'We want to travel',
'I like birdsong',
'Saturday',
'Mother-in-law',
'There are many suns in the universe',
'The skunks smell bad',
'You walk very fast (formal way of you)',
'to listen melodies',
'Friday',
'Father-in-law',
'The woman likes to wear dresses',
'He looks everywhere',
'she has three cats',
'You are right (omit subject pronoun - informal-you)',
'Thursday',
'Daughter-in-law',
'I have two brothers',
'A cup of tea',
'he teaches Spanish as a second language',
'This is an easy book to read',
'Wednesday',
'Son-in-law',
'A green tree',
'I\'m looking for you',
'You look  from your window (informal You)',
'The study of the human body',
'Tuesday',
'Aunt',
'The piano keys',
'Forbidden to turn right',
'I talk to her every morning',
'The wind blows hard',
'Monday',
'Uncle',
'The little pony',
'The girls play the piano',
'I want to go to the center, please (omit subject pronoun)',
'The way to the city',
'Bathroom',
'Niece',
'The pencil has no eraser',
'Measure the distance between two points (informal - imperative)',
'What is the name of this street?',
'What time does the bus come by?',
'Window',
'Nephew',
'How much is the skirt?',
'Brushes, paints and canvases',
'Where is there a restaurant?',
'We are afraid of that volcano (omit subject pronoun)',
'The door',
'Sister',
'Crabs walk sideways and backwards',
'We are hungry',
'What is the address of the hotel?',
'Who are you? (formal way of you)',
'Attic',
'Brother',
'The trains are modern',
'Today is a nice day',
'The child is thirsty',
'The bridge is located in the north of the city',
'Garage',
'Daughter',
'You have good luck',
'Forbidden to turn left',
'What time is it?',
'I don\'t remember how to do this (omit subject pronoun)',
'Roof',
'Son',
'The pages of the notebook',
'The child plays with a ball',
'A single fish',
'I stay at home',
'The floor',
'Father',
'An unknown place',
'I\'m at work',
'He repeats everything I say',
'The pictures are not in the album',
'Terrace',
'Mother',
'Mercury and Venus have no moons',
'The breakfast is served',
'The fork is clean',
'Please don\'t go away (informal way of you)',
'House',
'Granddaughter',
'The blue sea',
'It\'s very sunny',
'You speak German well',
'How are you? (omit subject pronoun)',
'The wall',
'Grandson',
'Where are you going?',
'Tell me a story (informal-you)',
'I love you very much (omit subject pronoun)',
'Saturday and Sunday are the weekend days',
'Roof',
'Grandmother',
'We don\'t want to do the homework',
'Iron the shirts (imperative)',
'The mountain is very high',
'Breakfast, lunch and dinner'


]