
export const ESPALABRAS: string[] = [
'El sótano',
'Abuelo',
'La biblioteca tiene muchos libros',
'Las cuerdas del arpa',
'Él escribe muy bien portugués',
'Trastero',
'Estaciones del año',
'No es fácil conseguir la dirección correcta',
'¿Dónde están mis lápices?',
'¿A qué hora sales del trabajo?',
'El balcón',
'Regiones',
'Los zapatos son muy bonitos',
'Un postre con fresas y melocotones',
'Cerrar',
'Corredor',
'Familia',
'El programa es perfecto',
'Plato con tenedor y cuchillo',
'Yo bebo agua',
'La cocina',
'Partes de la casa',
'El plato está sucio',
'Los carros antiguos',
'Ellos van a las montañas',
'Sala',
'Diciembre',
'Vamos a la playa esta tarde',
'Un vuelo a París',
'A la señora no le gusta bailar',
'Cuarto',
'Noviembre',
'Edad',
'Está lloviendo',
'El caballo tiene sed',
'Los pingüinos no vuelan',
'Octubre',
'Fecha de nacimiento',
'Ama la vida',
'Primavera, Verano, Otoño, Invierno',
'Ella dibuja una flor',
'Septiembre',
'Dirección',
'Los relojes están sincronizados',
'Teléfono móvil',
'Ella usa zapatos de tacón alto ',
'Agosto',
'Buenas noches',
'La sopa está muy fría',
'Adiós hasta luego',
'Los espirales en la naturaleza',
'Julio',
'Buenas tardes',
'Los caramelos son de menta',
'Hola',
'A ella le gusta sonreir',
'Junio',
'Buenos días',
'Un edificio alto',
'El último día laborable de la semana es el viernes',
'hay un solo cisne en el lago',
'A él le gusta caminar',
'Mayo',
'Bisnieta',
'A mí me gusta comer helado',
'El primer día laborable de la semana es el lunes',
'hay muchas palomas en la plaza',
'La casa es muy grande',
'Abril',
'Bisnieto',
'Los bosques son los pulmones del planeta',
'Los días de la semana',
'el gato es muy gordo',
'Mi avión sale en pocos minutos',
'Marzo',
'Cuñada',
'Un atardecer en la playa',
'Los idiomas',
'el perro no tiene nombre',
'Me gusta pintar',
'Febrero',
'Cuñado',
'Los alumnos estudian para el examen',
'Los países y las ciudades',
'A ellas no les gusta correr',
'No olvides cerrar',
'Enero',
'Prima',
'Ellos se quedan en casa',
'Las niñas no quieren jugar',
'A ellos les gusta nadar',
'Ella usa un lazo rosado',
'Domingo',
'Primo',
'A ella le gusta cantar',
'Las nubes están en el cielo',
'Nosotros queremos viajar',
'A mí me gusta el canto de los pájaros',
'Sábado',
'Suegra',
'Hay muchos soles en el universo',
'Los zorrillos huelen mal',
'Usted camina muy rápido',
'Escuchar melodías',
'Viernes',
'Suegro',
'A la mujer le gusta usar  vestidos',
'Él busca en todas partes',
'ella tiene tres gatos',
'Tienes razón',
'Jueves',
'Nuera',
'Yo tengo dos hermanos',
'Una taza de té',
'él enseña español como segunda lengua',
'Este es un libro fácil de leer',
'Miércoles',
'Yerno',
'Un árbol verde',
'Yo te estoy buscando',
'Tú miras desde tu ventana',
'El estudio del cuerpo humano',
'Martes',
'Tía',
'Las teclas del piano',
'Prohibido girar a la derecha',
'Yo hablo con ella todas las mañanas',
'El viento sopla fuerte',
'El lunes',
'Tío',
'El pequeño pony',
'Las niñas tocan el piano',
'Quiero ir al centro, por favor',
'El camino para la ciudad',
'Baño',
'Sobrina',
'El lápiz no tiene borrador',
'Mide la distancia entre dos puntos',
'¿Cuál es el nombre de esta calle?',
'¿A qué hora pasa el autobús?',
'Ventana',
'Sobrino',
'¿Cuanto cuesta la falda?',
'Pinceles, pinturas y lienzos',
'¿Dónde hay un restaurante?',
'Tenemos miedo de ese volcán',
'La puerta',
'Hermana',
'Los cangrejos caminan de lado y para atrás',
'Nosotros tenemos hambre',
'¿Cuál es la dirección del hotel?',
'¿Quién es usted?',
'ático',
'Hermano',
'Los trenes son modernos',
'Hoy es un bonito día',
'El niño tiene sed',
'El puente queda en el norte de la ciudad',
'Garaje',
'Hija',
'Tú tienes buena suerte',
'Prohibido girar a la izquierda',
'¿Qué hora es?',
'No recuerdo cómo se hace esto',
'Tejado',
'Hijo',
'Las páginas del cuaderno',
'El niño juega con una pelota',
'Un solo pez',
'Yo me quedo en casa',
'El piso',
'Padre',
'Un lugar desconocido',
'Yo estoy en el trabajo',
'Él repite todo lo que digo',
'Las fotos no están en el álbum',
'Terraza',
'Madre',
'Mercurio y Venus no tienen lunas',
'El desayuno está servido',
'El tenedor está limpio',
'Por favor, no te vayas',
'Casa',
'Nieta',
'El mar azul',
'Hace mucho sol',
'Tú hablas alemán bien',
'¿Cómo estás?',
'La pared',
'Nieto',
'¿Para dónde vas?',
'Cuéntame un cuento',
'Te quiero mucho',
'El sábado y el domingo son los días del fin de semana',
'Techo',
'Abuela',
'No queremos hacer la tarea',
'Plancha las camisas',
'La montaña es muy alta',
'Desayuno, almuerzo y cena'


];