import { Letrasdeaudiopt } from './letrasdeaudiopt';

export const LETRASDEAUDIOSPT: Letrasdeaudiopt[] = [


{ nivel: 'avanzadopt', nro:1 , frasePT:'A testemunho não se recorda bem dos factos ocorridos', fraseEN:'The witness has a poor memory of the events that occurred' },
{ nivel: 'avanzadopt', nro:2 , frasePT:'Restam 24 minutos e 13 segundos para o fim do jogo', fraseEN:'24 minutes and 13 seconds left until the end of the match' },
{ nivel: 'avanzadopt', nro:3 , frasePT:'O protagonista deste filme é o mesmo que o protagonista da série televisiva', fraseEN:'The protagonist of this film is the same as the one in the television series' },
{ nivel: 'avanzadopt', nro:4 , frasePT:'A jornalista especializou-se em desvendar mistérios e casos fraudulentos', fraseEN:'The journalist specializes in uncovering mysteries and fraudulent cases' },
{ nivel: 'avanzadopt', nro:5 , frasePT:'As profecias foram escritas para que não se cumprissem', fraseEN:'Prophecies were written for not to be fulfilled' },
{ nivel: 'avanzadopt', nro:6 , frasePT:'O destino deu-te uma segunda oportunidade, aproveita-a bem', fraseEN:'Fate gave you a second chance, take good advantage of it' },
{ nivel: 'avanzadopt', nro:7 , frasePT:'Os multiversos são os universos paralelos que são gerados com cada decisão que tomamos', fraseEN:'Multiverses are the parallel universes that are generated with every decision we make' },
{ nivel: 'avanzadopt', nro:8 , frasePT:'Todos os objectos estão etiquetados de acordo com a sua categoria de utilização', fraseEN:'All the objects are labeled according to their category of use' },
{ nivel: 'avanzadopt', nro:9 , frasePT:'Eles estão a cozinhar a comida para o evento do fim-de-semana', fraseEN:'They are cooking the food for the weekend event' },
{ nivel: 'avanzadopt', nro:10 , frasePT:'A escada tem muitos degraus. Tu sobes, eu espero por ti aqui em baixo', fraseEN:'The staircase has many steps, you go up, I will wait for you down here' },
{ nivel: 'avanzadopt', nro:11 , frasePT:'O rei pediu uma interpretação do horóscopo ao astrólogo da corte', fraseEN:'The king requested an interpretation of the horoscope from the court astrologer' },
{ nivel: 'avanzadopt', nro:12 , frasePT:'A armadura do último cavaleiro está exposta no museu do castelo', fraseEN:'The armor of the last knight is exhibited in the castle museum' },
{ nivel: 'avanzadopt', nro:13 , frasePT:'Nas margens das páginas do livro, escrevo anotações das frases de que gosto', fraseEN:'In the margins of the pages of the book I write annotations of phrases that I like' },
{ nivel: 'avanzadopt', nro:14 , frasePT:'Estou de volta à cidade. É noite e estou à procura da morada da casa do meu amigo', fraseEN:'I am back in the city. It is night and I am looking for the address of my friend\'s house' },
{ nivel: 'avanzadopt', nro:15 , frasePT:'O jogador de futebol foi o melhor jogador da temporada e recebeu muitas ofertas de outras equipas', fraseEN:'The soccer player was the best of the season and received many offers from other teams' },
{ nivel: 'avanzadopt', nro:16 , frasePT:'Telefonei a todos os convidados para confirmar a sua presença na festa', fraseEN:'I telephoned all the guests to confirm their attendance to the party' },
{ nivel: 'avanzadopt', nro:17 , frasePT:'O jovem é uma pessoa muito solitária que gosta de música instrumental', fraseEN:'The young man is a very lonely person who enjoys instrumental music' },
{ nivel: 'avanzadopt', nro:18 , frasePT:'Ao chegar à pequena aldeia, tive a sensação de que eu viajei no tempo, tudo era muito antigo', fraseEN:'Arriving in the small town I had the feeling that I had traveled back in time, everything was very ancient' },
{ nivel: 'avanzadopt', nro:19 , frasePT:'A praça fica em frente ao edifício da Câmara Municipal e tem uma fonte de água', fraseEN:'The square is in front of the mayor\'s building and has a water fountain' },
{ nivel: 'avanzadopt', nro:20 , frasePT:'Encontrou duas pessoas que chamaram a sua atenção devido às suas feições estranhas e à sua grande altura', fraseEN:'He found two people who caught his attention because of their strange features and great height' },
{ nivel: 'avanzadopt', nro:21 , frasePT:'A lenda diz que o canto das sereias encanta os marinheiros e aprisiona-os', fraseEN:'According to the legend, the song of the mermaids enchants the sailors and traps them' },
{ nivel: 'avanzadopt', nro:22 , frasePT:'Felizmente, tudo correu bem e os médicos salvaram o doente', fraseEN:'Fortunately, everything turned out well and the doctors saved the patient' },
{ nivel: 'avanzadopt', nro:23 , frasePT:'Parece uma grande coincidência que todos chegaram ao banquete ao mesmo tempo', fraseEN:'It seems very coincidental that they all arrived at the banquet at the same time' },
{ nivel: 'avanzadopt', nro:24 , frasePT:'O mosteiro foi fundado por um monge na antiguidade e nele se conservam muitos manuscritos', fraseEN:'The monastery was founded by a monk in ancient times, and many manuscripts are preserved there' },
{ nivel: 'avanzadopt', nro:25 , frasePT:'O fumo negro saía da chaminé, sinal de que alguém estava na cabana', fraseEN:'A black smoke was coming out of the chimney, a sign that someone was in the cabin' },
{ nivel: 'avanzadopt', nro:26 , frasePT:'Cheguei à morada, a porta estava aberta, não havia ninguém no interior do apartamento', fraseEN:'I arrived at the address, the door was open, there was no one inside the apartment' },
{ nivel: 'avanzadopt', nro:27 , frasePT:'A opinião de todos é que o programa foi excessivamente longo e aborrecido', fraseEN:'Everyone\'s opinion is that the program was excessively long and boring' },
{ nivel: 'avanzadopt', nro:28 , frasePT:'O excesso de trabalho esgotou a equipa e levou-a a desistir', fraseEN:'The overwork exhausted the team and made them quit' },
{ nivel: 'avanzadopt', nro:29 , frasePT:'O café tinha um estilo retro, com poltronas almofadadas e cores vivas', fraseEN:'The cafeteria had a retro style with cushioned armchairs and garish colors' },
{ nivel: 'avanzadopt', nro:30 , frasePT:'O pequeno-almoço é servido e é composto por torradas e ovos', fraseEN:'Breakfast was served and consisted of toast and eggs' },
{ nivel: 'avanzadopt', nro:31 , frasePT:'Na mudança, perderam-se e partiram-se muitos objectos', fraseEN:'In the move many items were lost and others were broken' },
{ nivel: 'avanzadopt', nro:32 , frasePT:'Curiosamente, ambos tinham a mesma idade e o mesmo gosto musical', fraseEN:'Interestingly, both were the same age and had the same taste in music' },
{ nivel: 'avanzadopt', nro:33 , frasePT:'A visão do governador difere do que os residentes querem', fraseEN:'The governor\'s vision differs from what the locals want' },
{ nivel: 'avanzadopt', nro:34 , frasePT:'O guitarrista é excepcional, mas o baterista é muito mau', fraseEN:'The guitarist is exceptional but the drummer is very bad' },
{ nivel: 'avanzadopt', nro:35 , frasePT:'A paisagem tinha uma perspectiva interessante e cores pastel', fraseEN:'The landscape had an interesting perspective and pastel colors' },
{ nivel: 'avanzadopt', nro:36 , frasePT:'Antes de mais, não te estou a atacar, estou apenas a dar-te alguns conselhos', fraseEN:'First of all I am not attacking you I am just giving you advice' },
{ nivel: 'avanzadopt', nro:37 , frasePT:'A acção foi resolvida por acordo amigável fora do tribunal', fraseEN:'The lawsuit was settled out of court with an friendly settlement' },
{ nivel: 'avanzadopt', nro:38 , frasePT:'Eles decidiram tomar as rédeas da empresa após a morte do pai.', fraseEN:'They decided to take over the business after the father\'s death' },
{ nivel: 'avanzadopt', nro:39 , frasePT:'Todos os veleiros prontos para a regata do próximo fim-de-semana', fraseEN:'All sailboats are ready for the regatta next weekend' },
{ nivel: 'avanzadopt', nro:40 , frasePT:'Subscreva-se ao canal e recorde-se de gostar dos vídeos', fraseEN:'Subscribe to the channel and remember to like the videos' },
{ nivel: 'avanzadopt', nro:41 , frasePT:'O guarda-redes fez uma falsa partida e o jogador adversário marcou um golo', fraseEN:'The goalkeeper came out in false start and the opposing team\'s player scored a goal' },
{ nivel: 'avanzadopt', nro:42 , frasePT:'O realizador do filme não o quer como personagem principal', fraseEN:'The director of the movie doesn\'t want him as the protagonist' },
{ nivel: 'avanzadopt', nro:43 , frasePT:'O técnico de som não chegou a tempo, tivemos de esperar por ele', fraseEN:'The sound technician didn\'t arrive on time, we had to wait for him' },
{ nivel: 'avanzadopt', nro:44 , frasePT:'Embora ele tenha muito talento, é difícil trabalhar com ele', fraseEN:'Although he is very talented, he is very difficult to work with' },
{ nivel: 'avanzadopt', nro:45 , frasePT:'Escolha bem o seu companheiro, não caia numa relação tóxica', fraseEN:'Choose well who you are going to be with don\'t fall into a toxic relationship' },
{ nivel: 'avanzadopt', nro:46 , frasePT:'Este guisado é muito saboroso, tem a quantidade perfeita de sal', fraseEN:'This stew is very tasty it has the perfect salt point' },
{ nivel: 'avanzadopt', nro:47 , frasePT:'É uma batalha entre o velho e o novo modo de vida', fraseEN:'It is a battle between the old and the new ways of living' },
{ nivel: 'avanzadopt', nro:48 , frasePT:'Os objectos de leilão passaram por um controlo e possuem uma licença de proveniência', fraseEN:'The auction items have undergone controls and have their origin license' },
{ nivel: 'intermediopt', nro:1 , frasePT:'Boa tarde. Gostaria de tomar um café?', fraseEN:'Good afternoon. Would you like to drink a coffee?' },
{ nivel: 'intermediopt', nro:2 , frasePT:'A pergunta foi respondida correctamente', fraseEN:'The question was answered correctly' },
{ nivel: 'intermediopt', nro:3 , frasePT:'É uma pessoa maravilhosa', fraseEN:'Is a wonderful person' },
{ nivel: 'intermediopt', nro:4 , frasePT:'Tu sabes que sem óculos não consigo ver bem', fraseEN:'You know that without glasses I can\'t see well' },
{ nivel: 'intermediopt', nro:5 , frasePT:'A música do filme é muito bonita e alegre', fraseEN:'The music of the movie is very beautiful and cheerful' },
{ nivel: 'intermediopt', nro:6 , frasePT:'Esta é uma lição muito difícil', fraseEN:'This is a very difficult lesson' },
{ nivel: 'intermediopt', nro:7 , frasePT:'Todas as coisas podem ser melhoradas', fraseEN:'All things can be improved' },
{ nivel: 'intermediopt', nro:8 , frasePT:'Os políticos foram agressivos no debate', fraseEN:'The politicians were aggressive in the debate' },
{ nivel: 'intermediopt', nro:9 , frasePT:'A primeira hora foi aborrecida', fraseEN:'The first half hour was boring' },
{ nivel: 'intermediopt', nro:10 , frasePT:'Tenho frio, dá-me esse cobertor de lã. Por favor.', fraseEN:'I am cold, give me that wool blanket. Please' },
{ nivel: 'intermediopt', nro:11 , frasePT:'O detective resolveu o caso', fraseEN:'The detective solved the case' },
{ nivel: 'intermediopt', nro:12 , frasePT:'Competiu com grande vigor', fraseEN:'Competed with a lot of vigor' },
{ nivel: 'intermediopt', nro:13 , frasePT:'Isso é uma lenda urbana', fraseEN:'That is an urban legend' },
{ nivel: 'intermediopt', nro:14 , frasePT:'Estou no comboio a caminho da cidade', fraseEN:'I am on the train on my way to the city' },
{ nivel: 'intermediopt', nro:15 , frasePT:'No museu restam dois quadros do famoso pintor', fraseEN:'In the museum there are still two paintings by the famous painter' },
{ nivel: 'intermediopt', nro:16 , frasePT:'No Outono de 1950, nasceu o meu avô', fraseEN:'In the autumn of 1950 my grandfather was born' },
{ nivel: 'intermediopt', nro:17 , frasePT:'O jornalista gravou a entrevista e depois transcreveu-a', fraseEN:'The journalist recorded the interview and then transcribed it' },
{ nivel: 'intermediopt', nro:18 , frasePT:'A música expressa a alma do artista', fraseEN:'The music expresses the soul of the artist' },
{ nivel: 'intermediopt', nro:19 , frasePT:'A pintura tem tons vermelhos e alaranjados', fraseEN:'The painting has red and orange tones' },
{ nivel: 'intermediopt', nro:20 , frasePT:'Eu convidei meu amigo para comer no melhor restaurante da cidade', fraseEN:'I invited my friend to eat at the best restaurant in town' },
{ nivel: 'intermediopt', nro:21 , frasePT:'Quando falei com o escritor, ele contou-me tudo sobre a história do seu livro', fraseEN:'When I talked to the writer, he told me all about the story of his book' },
{ nivel: 'intermediopt', nro:22 , frasePT:'Os seus pais são professores universitários na Faculdade de Ciências', fraseEN:'His parents are university professors at the faculty of science' },
{ nivel: 'intermediopt', nro:23 , frasePT:'Os cisnes estão no lago', fraseEN:'The swans are on the lake' },
{ nivel: 'intermediopt', nro:24 , frasePT:'As guerras nunca são boas', fraseEN:'Wars are never good' },
{ nivel: 'intermediopt', nro:25 , frasePT:'A caixa de música tem uma pequena bailarina', fraseEN:'The music box has a little dancer' },
{ nivel: 'intermediopt', nro:26 , frasePT:'A ponte de madeira atravessa o rio', fraseEN:'The wooden bridge crosses the river' },
{ nivel: 'intermediopt', nro:27 , frasePT:'O tio foi procurar os sobrinhos depois da escola', fraseEN:'The uncle looked for his nephews at the school exit' },
{ nivel: 'intermediopt', nro:28 , frasePT:'A aluna está atenta a todas as palavras do professor', fraseEN:'The female student is aware of all the teacher\'s words' },
{ nivel: 'intermediopt', nro:29 , frasePT:'Desde que tem insónias, fica acordado toda a noite', fraseEN:'Since he has insomnia he stays awake all night long' },
{ nivel: 'intermediopt', nro:30 , frasePT:'Encontrei uma gaveta cheia de fotografias e cartas que pertenciam aos meus avós', fraseEN:'I found a drawer full of photos and letters that belonged to my grandparents' },
{ nivel: 'intermediopt', nro:31 , frasePT:'A história era contraditória do princípio ao fim', fraseEN:'The story was contradictory from beginning to end' },
{ nivel: 'intermediopt', nro:32 , frasePT:'Num dia como outro qualquer, nada fazia prever o que tinha acontecido ao cantor', fraseEN:'One day like any other, nothing foreshadowed what happened with the singer' },
{ nivel: 'intermediopt', nro:33 , frasePT:'Vi o meu reflexo no espelho e fiquei satisfeita com o penteado', fraseEN:'I saw my reflection in the mirror and was pleased with the hairstyle' },
{ nivel: 'intermediopt', nro:34 , frasePT:'Estas minas de carvão foram encerradas por razões de segurança', fraseEN:'Those coal mines were closed down for safety reasons' },
{ nivel: 'intermediopt', nro:35 , frasePT:'Há muitas beringelas no pomar', fraseEN:'There are a lot of eggplants in the orchard' },
{ nivel: 'intermediopt', nro:36 , frasePT:'Trabalhei nessa empresa durante quatro anos e meio', fraseEN:'I worked in that company for four and a half years' },
{ nivel: 'intermediopt', nro:37 , frasePT:'Tem cuidado, isso parece ser um culto', fraseEN:'Be careful, that looks like a cult' },
{ nivel: 'intermediopt', nro:38 , frasePT:'Gostarias de ir jantar fora comigo?', fraseEN:'Would you like to go out to dinner with me?' },
{ nivel: 'intermediopt', nro:39 , frasePT:'No coro há sopranos, altos, tenores e baixos', fraseEN:'In the choir there are sopranos, contraltos, tenors and basses.' },
{ nivel: 'intermediopt', nro:40 , frasePT:'O extintor funcionou na perfeição e apagou o fogo', fraseEN:'The fire extinguisher worked perfectly and put out the fire' },
{ nivel: 'intermediopt', nro:41 , frasePT:'Gosto muito do projecto e quero fazer parte dele', fraseEN:'I really like the project I want to be part of it' },
{ nivel: 'intermediopt', nro:42 , frasePT:'Toda a conversa girou em torno da sua vida amorosa', fraseEN:'The whole conversation centered around her love life' },
{ nivel: 'intermediopt', nro:43 , frasePT:'Por favor, lave a loiça depois de terminar a sua refeição', fraseEN:'Please wash the dishes after finishing your meal' },
{ nivel: 'intermediopt', nro:44 , frasePT:'O futebol é jogado com uma bola e o basebol com um taco e uma bola', fraseEN:'Soccer is played with a soccer ball and baseball with a bat and ball' },
{ nivel: 'intermediopt', nro:45 , frasePT:'Por favor, vem comigo, não gosto de estar sozinha', fraseEN:'Please stay with me, I don\'t like to be alone' },
{ nivel: 'intermediopt', nro:46 , frasePT:'Elas são amigas íntimas e apoiam-se mutuamente', fraseEN:'They are close friends and support each other' },
{ nivel: 'intermediopt', nro:47 , frasePT:'Não quero julgar se estás certo ou errado', fraseEN:'I don\'t want to judge whether you are right or wrong' },
{ nivel: 'principiantept', nro:1 , frasePT:'Bom dia', fraseEN:'Good morning' },
{ nivel: 'principiantept', nro:2 , frasePT:'Como é que está?', fraseEN:'How are you?' },
{ nivel: 'principiantept', nro:3 , frasePT:'Ela gosta de cantar', fraseEN:'She likes to sing' },
{ nivel: 'principiantept', nro:4 , frasePT:'Procurar uma camisa', fraseEN:'Search for a shirt' },
{ nivel: 'principiantept', nro:5 , frasePT:'Amar a vida', fraseEN:'Love life' },
{ nivel: 'principiantept', nro:6 , frasePT:'Gosto muito de ti', fraseEN:'I love you so much' },
{ nivel: 'principiantept', nro:7 , frasePT:'Gosto de comer gelado', fraseEN:'I like to eat ice cream' },
{ nivel: 'principiantept', nro:8 , frasePT:'Um edifício alto', fraseEN:'A high building' },
{ nivel: 'principiantept', nro:9 , frasePT:'Uma casa muito bonita', fraseEN:'A very beautiful house' },
{ nivel: 'principiantept', nro:10 , frasePT:'Faz muito sol', fraseEN:'It is very sunny' },
{ nivel: 'principiantept', nro:11 , frasePT:'Hoje é um dia bonito', fraseEN:'Today is a lovely day' },
{ nivel: 'principiantept', nro:12 , frasePT:'Conta-me uma história', fraseEN:'Tell me a story' },
{ nivel: 'principiantept', nro:13 , frasePT:'Desenhar uma flor', fraseEN:'Draw a flower' },
{ nivel: 'principiantept', nro:14 , frasePT:'Que horas são?', fraseEN:'What time is it?' },
{ nivel: 'principiantept', nro:15 , frasePT:'Ficar em casa', fraseEN:'stay in your home' },
{ nivel: 'principiantept', nro:16 , frasePT:'Está a chover', fraseEN:'It is raining' },
{ nivel: 'principiantept', nro:17 , frasePT:'Um voo para Paris', fraseEN:'A flight to Paris' },
{ nivel: 'principiantept', nro:18 , frasePT:'Gosto de pintar', fraseEN:'I like to paint' },
{ nivel: 'principiantept', nro:19 , frasePT:'O pequeno pónei', fraseEN:'The Little Pony' },
{ nivel: 'principiantept', nro:20 , frasePT:'Ouvir melodias', fraseEN:'Listening to melodies' },
{ nivel: 'principiantept', nro:21 , frasePT:'Um pôr-do-sol na praia', fraseEN:'A sunset on the beach' },
{ nivel: 'principiantept', nro:22 , frasePT:'O mar azul', fraseEN:'The blue sea' },
{ nivel: 'principiantept', nro:23 , frasePT:'Uma árvore verde', fraseEN:'A green tree' },
{ nivel: 'principiantept', nro:24 , frasePT:'Um sorriso bonito', fraseEN:'A beautiful smile' },
{ nivel: 'principiantept', nro:25 , frasePT:'As páginas do caderno', fraseEN:'The pages of the notebook' },
{ nivel: 'principiantept', nro:26 , frasePT:'A montanha é muito alta', fraseEN:'The mountain is very high' },
{ nivel: 'principiantept', nro:27 , frasePT:'As teclas do piano', fraseEN:'The piano keys' },
{ nivel: 'principiantept', nro:28 , frasePT:'Quem és tu?', fraseEN:'Who are you?' },
{ nivel: 'principiantept', nro:29 , frasePT:'Onde é que vai?', fraseEN:'Where are you going?' },
{ nivel: 'principiantept', nro:30 , frasePT:'Estou à tua procura', fraseEN:'I am looking for you' },
{ nivel: 'principiantept', nro:31 , frasePT:'Uma chávena de chá', fraseEN:'A cup of tea' },
{ nivel: 'principiantept', nro:32 , frasePT:'As fotografias são lindas', fraseEN:'The photos are beautiful' },
{ nivel: 'principiantept', nro:33 , frasePT:'Uma terapia musical', fraseEN:'A musical therapy' },
{ nivel: 'principiantept', nro:34 , frasePT:'O canto dos pássaros', fraseEN:'The singing of the birds' },
{ nivel: 'principiantept', nro:35 , frasePT:'A neve cobriu toda a paisagem', fraseEN:'The snow has covered the whole landscape' },
{ nivel: 'principiantept', nro:36 , frasePT:'O casaco azul', fraseEN:'The blue coat' },
{ nivel: 'principiantept', nro:37 , frasePT:'Há um longo caminho', fraseEN:'There is a very long road' },
{ nivel: 'principiantept', nro:38 , frasePT:'Bons sonhos enquanto dorme', fraseEN:'Sweet dreams of sleep' },
{ nivel: 'principiantept', nro:39 , frasePT:'A roupa está no roupeiro', fraseEN:'The clothes are in the closet' },
{ nivel: 'principiantept', nro:40 , frasePT:'Há flores no jardim', fraseEN:'There are flowers in the garden' },
{ nivel: 'principiantept', nro:41 , frasePT:'Muitos frutos para comer', fraseEN:'Lots of fruits to eat' },
{ nivel: 'principiantept', nro:42 , frasePT:'A mãe é carinhosa', fraseEN:'The mother is loving' },
{ nivel: 'principiantept', nro:43 , frasePT:'O livro está escrito em verso', fraseEN:'The book is written in verse' },
{ nivel: 'principiantept', nro:44 , frasePT:'Não gosto dessa canção', fraseEN:'I don\'t like that song' }

	
];
