import { Letrasdeaudio } from './letrasdeaudio';

export const LETRASDEAUDIOS: Letrasdeaudio[] = [


{ nivel: 'avanzado', nro:1 , fraseES:'El testigo no recuerda bien los sucesos ocurridos', fraseEN:'The witness has a poor memory of the events that occurred' },
{ nivel: 'avanzado', nro:2 , fraseES:'Quedan 24 minutos y 13 segundos para que finalice el partido ', fraseEN:'24 minutes and 13 seconds left until the end of the match' },
{ nivel: 'avanzado', nro:3 , fraseES:'El protagonista de esta película es el mismo de la serie de televisión', fraseEN:'The protagonist of this film is the same as the one in the television series' },
{ nivel: 'avanzado', nro:4 , fraseES:'El periodista se especializa en desvelar misterios y casos fraudulentos', fraseEN:'The journalist specializes in uncovering mysteries and fraudulent cases' },
{ nivel: 'avanzado', nro:5 , fraseES:'Las profecías fueron escritas para que no se cumplan', fraseEN:'Prophecies were written for not to be fulfilled' },
{ nivel: 'avanzado', nro:6 , fraseES:'El destino te dio una segunda oportunidad, aprovéchala bien', fraseEN:'Fate gave you a second chance, take good advantage of it' },
{ nivel: 'avanzado', nro:7 , fraseES:'Los multiversos son los universos paralelos que se generan con cada decisión que tomamos', fraseEN:'Multiverses are the parallel universes that are generated with every decision we make' },
{ nivel: 'avanzado', nro:8 , fraseES:'Todos los objetos están etiquetados de acuerdo a su categoría de uso', fraseEN:'All the objects are labeled according to their category of use' },
{ nivel: 'avanzado', nro:9 , fraseES:'Ellos están cocinando la comida para el evento del fin de semana', fraseEN:'They are cooking the food for the weekend event' },
{ nivel: 'avanzado', nro:10 , fraseES:'La escalera tiene muchos escalones. Sube tú, yo te espero aquí abajo.', fraseEN:'The staircase has many steps, you go up, I will wait for you down here' },
{ nivel: 'avanzado', nro:11 , fraseES:'El rey pidió una interpretación del horóscopo al astrólogo de la corte.', fraseEN:'The king requested an interpretation of the horoscope from the court astrologer' },
{ nivel: 'avanzado', nro:12 , fraseES:'La armadura del último caballero está exhibida en el museo del castillo', fraseEN:'The armor of the last knight is exhibited in the castle museum' },
{ nivel: 'avanzado', nro:13 , fraseES:'En los márgenes de las páginas del libro escribo anotaciones de las frases que me gustan', fraseEN:'In the margins of the pages of the book I write annotations of phrases that I like' },
{ nivel: 'avanzado', nro:14 , fraseES:'Estoy de nuevo en la ciudad. Es de noche y estoy buscando la dirección de la casa de mi amigo', fraseEN:'I am back in the city. It is night and I am looking for the address of my friend\'s house' },
{ nivel: 'avanzado', nro:15 , fraseES:'El jugador de fútbol fue el mejor de la temporada y recibió muchas ofertas de otros equipos', fraseEN:'The soccer player was the best of the season and received many offers from other teams' },
{ nivel: 'avanzado', nro:16 , fraseES:'Llamé por teléfono a todos los invitados para confirmar su asistencia a la fiesta', fraseEN:'I telephoned all the guests to confirm their attendance to the party' },
{ nivel: 'avanzado', nro:17 , fraseES:'El joven es una persona muy solitaria que disfruta la música instrumental', fraseEN:'The young man is a very lonely person who enjoys instrumental music' },
{ nivel: 'avanzado', nro:18 , fraseES:'Al llegar al pequeño pueblo tuve la sensación de que viajé en el tiempo, todo era muy antiguo', fraseEN:'Arriving in the small town I had the feeling that I had traveled back in time, everything was very ancient' },
{ nivel: 'avanzado', nro:19 , fraseES:'La plaza está frente al edificio de la alcaldía y tiene una fuente de agua', fraseEN:'The square is in front of the mayor\'s building and has a water fountain' },
{ nivel: 'avanzado', nro:20 , fraseES:'Encontró dos personas que llamaron su atención por sus extraños rasgos y gran altura', fraseEN:'He found two people who caught his attention because of their strange features and great height' },
{ nivel: 'avanzado', nro:21 , fraseES:'La leyenda cuenta que el canto de las sirenas encanta a los marineros y los atrapa', fraseEN:'According to the legend, the song of the mermaids enchants the sailors and traps them' },
{ nivel: 'avanzado', nro:22 , fraseES:'Afortunadamente todo se solucionó bien y los médicos salvaron al paciente', fraseEN:'Fortunately, everything turned out well and the doctors saved the patient' },
{ nivel: 'avanzado', nro:23 , fraseES:'Parece mucha casualidad que todos llegaron al mismo tiempo al banquete', fraseEN:'It seems very coincidental that they all arrived at the banquet at the same time' },
{ nivel: 'avanzado', nro:24 , fraseES:'El monasterio fue fundado por un monje en la antigüedad, y allí se conservan muchos manuscritos', fraseEN:'The monastery was founded by a monk in ancient times, and many manuscripts are preserved there' },
{ nivel: 'avanzado', nro:25 , fraseES:'Un humo negro salía por la chimenea, señal de que alguien estaba en la cabaña', fraseEN:'A black smoke was coming out of the chimney, a sign that someone was in the cabin' },
{ nivel: 'avanzado', nro:26 , fraseES:'Llegué a la dirección, la puerta estaba abierta, no había nadie dentro del apartamento', fraseEN:'I arrived at the address, the door was open, there was no one inside the apartment' },
{ nivel: 'avanzado', nro:27 , fraseES:'La opinión de todos es que el programa fue excesivamente largo y aburrido', fraseEN:'Everyone\'s opinion is that the program was excessively long and boring' },
{ nivel: 'avanzado', nro:28 , fraseES:'El exceso de trabajo agotó al equipo y los hizo renunciar', fraseEN:'The overwork exhausted the team and made them quit' },
{ nivel: 'avanzado', nro:29 , fraseES:'La cafetería tenía un estilo retro con sillones acolchados y colores chillones', fraseEN:'The cafeteria had a retro style with cushioned armchairs and garish colors' },
{ nivel: 'avanzado', nro:30 , fraseES:'El desayuno está servido y consta de tostadas y huevos', fraseEN:'Breakfast was served and consisted of toast and eggs' },
{ nivel: 'avanzado', nro:31 , fraseES:'En la mudanza se perdieron muchos objetos y otros se rompieron', fraseEN:'In the move many items were lost and others were broken' },
{ nivel: 'avanzado', nro:32 , fraseES:'Curiosamente ambos tenían la misma edad y gusto por la música', fraseEN:'Interestingly, both were the same age and had the same taste in music' },
{ nivel: 'avanzado', nro:33 , fraseES:'La visión del gobernador difiere de lo que quieren los habitantes', fraseEN:'The governor\'s vision differs from what the locals want' },
{ nivel: 'avanzado', nro:34 , fraseES:'El guitarrista es excepcional pero el baterista es muy malo', fraseEN:'The guitarist is exceptional but the drummer is very bad' },
{ nivel: 'avanzado', nro:35 , fraseES:'El paisaje tenía una interesante perspectiva y colores pasteles', fraseEN:'The landscape had an interesting perspective and pastel colors' },
{ nivel: 'avanzado', nro:36 , fraseES:'En primer lugar yo no te estoy atacando solo te estoy dando un consejo', fraseEN:'First of all I am not attacking you I am just giving you advice' },
{ nivel: 'avanzado', nro:37 , fraseES:'La demanda se solucionó con un acuerdo amistoso fuera del tribunal', fraseEN:'The lawsuit was settled out of court with an friendly settlement' },
{ nivel: 'avanzado', nro:38 , fraseES:'Ellos decidieron tomar las riendas del negocio tras la muerte del padre', fraseEN:'They decided to take over the business after the father\'s death' },
{ nivel: 'avanzado', nro:39 , fraseES:'Todos los veleros están listos para la regata del próximo fin de semana', fraseEN:'All sailboats are ready for the regatta next weekend' },
{ nivel: 'avanzado', nro:40 , fraseES:'Suscríbete al canal y recuerda darle me gusta a los videos', fraseEN:'Subscribe to the channel and remember to like the videos' },
{ nivel: 'avanzado', nro:41 , fraseES:'El arquero salió en falso y el jugador del equipo contrario anotó un gol', fraseEN:'The goalkeeper came out in false start and the opposing team\'s player scored a goal' },
{ nivel: 'avanzado', nro:42 , fraseES:'El director de la película no lo quiere a él como protagonista', fraseEN:'The director of the movie doesn\'t want him as the protagonist' },
{ nivel: 'avanzado', nro:43 , fraseES:'El volcán hizo erupción pero afortunadamente el pueblo había sido evacuado', fraseEN:'The volcano erupted but fortunately the town had been evacuated' },
{ nivel: 'avanzado', nro:44 , fraseES:'El técnico de sonido no llegó a tiempo, tuvimos que esperarlo', fraseEN:'The sound technician didn\'t arrive on time, we had to wait for him' },
{ nivel: 'avanzado', nro:45 , fraseES:'Aunque tiene mucho talento, es muy difícil trabajar con él', fraseEN:'Although he is very talented, he is very difficult to work with"' },
{ nivel: 'avanzado', nro:46 , fraseES:'Elige bien con quien vas a estar, no caigas en una relación tóxica', fraseEN:'Choose well who you are going to be with don\'t fall into a toxic relationship' },
{ nivel: 'avanzado', nro:47 , fraseES:'Este guiso está muy sabroso, tiene el punto de sal perfecto', fraseEN:'This stew is very tasty it has the perfect salt point' },
{ nivel: 'avanzado', nro:48 , fraseES:'Es una batalla entre lo antiguo y las nuevas formas de vivir', fraseEN:'It is a battle between the old and the new ways of living' },
{ nivel: 'avanzado', nro:49 , fraseES:'Los objetos de la subasta han pasado por controles y cuentan con su licencia de procedencia', fraseEN:'The auction items have undergone controls and have their origin license' },
{ nivel: 'intermedio', nro:1 , fraseES:'Buenas tardes. ¿Te gustaría tomar un café?', fraseEN:'Good afternoon. Would you like to drink a coffee?' },
{ nivel: 'intermedio', nro:2 , fraseES:'La  pregunta fue contestada correctamente', fraseEN:'The question was answered correctly' },
{ nivel: 'intermedio', nro:3 , fraseES:'Es una persona maravillosa', fraseEN:'Is a wonderful person' },
{ nivel: 'intermedio', nro:4 , fraseES:'Tú sabes que sin anteojos no veo bien', fraseEN:'You know that without glasses I can\'t see well' },
{ nivel: 'intermedio', nro:5 , fraseES:'La música de la película es muy hermosa y alegre', fraseEN:'The music of the movie is very beautiful and cheerful' },
{ nivel: 'intermedio', nro:6 , fraseES:'Esta es una lección muy difícil', fraseEN:'This is a very difficult lesson' },
{ nivel: 'intermedio', nro:7 , fraseES:'Todas las cosas se pueden mejorar', fraseEN:'All things can be improved' },
{ nivel: 'intermedio', nro:8 , fraseES:'Los políticos estuvieron agresivos en el debate', fraseEN:'The politicians were aggressive in the debate' },
{ nivel: 'intermedio', nro:9 , fraseES:'La primera media hora fue aburrida', fraseEN:'The first half hour was boring' },
{ nivel: 'intermedio', nro:10 , fraseES:'Tengo frío, dame esa cobija de lana. Por favor.', fraseEN:'I am cold, give me that wool blanket. Please' },
{ nivel: 'intermedio', nro:11 , fraseES:'El detective resolvió el caso', fraseEN:'The detective solved the case' },
{ nivel: 'intermedio', nro:12 , fraseES:'Compitió con mucho vigor', fraseEN:'Competed with a lot of vigor' },
{ nivel: 'intermedio', nro:13 , fraseES:'Esa es una leyenda urbana', fraseEN:'That is an urban legend' },
{ nivel: 'intermedio', nro:14 , fraseES:'Estoy en el tren de camino a la ciudad', fraseEN:'I am on the train on my way to the city' },
{ nivel: 'intermedio', nro:15 , fraseES:'En el museo quedan dos cuadros del afamado pintor', fraseEN:'In the museum there are still two paintings by the famous painter' },
{ nivel: 'intermedio', nro:16 , fraseES:'En otoño de 1950 nació mi abuelo', fraseEN:'In the autumn of 1950 my grandfather was born' },
{ nivel: 'intermedio', nro:17 , fraseES:'El periodista grabó la entrevista y luego la transcribió', fraseEN:'The journalist recorded the interview and then transcribed it' },
{ nivel: 'intermedio', nro:18 , fraseES:'La música expresa el alma del artista', fraseEN:'The music expresses the soul of the artist' },
{ nivel: 'intermedio', nro:19 , fraseES:'El cuadro tiene tonos rojos y anaranjados', fraseEN:'The painting has red and orange tones' },
{ nivel: 'intermedio', nro:20 , fraseES:'Invité a mi amiga a comer en el mejor restaurante de la ciudad', fraseEN:'I invited my friend to eat at the best restaurant in town' },
{ nivel: 'intermedio', nro:21 , fraseES:'Cuando hablé con el escritor me contó todo sobre la historia de su libro', fraseEN:'When I talked to the writer, he told me all about the story of his book' },
{ nivel: 'intermedio', nro:22 , fraseES:'Los padres de él son profesores universitarios en la facultad de ciencias', fraseEN:'His parents are university professors at the faculty of science' },
{ nivel: 'intermedio', nro:23 , fraseES:'Los cisnes están en el lago', fraseEN:'The swans are on the lake' },
{ nivel: 'intermedio', nro:24 , fraseES:'Las guerras nunca son buenas', fraseEN:'Wars are never good' },
{ nivel: 'intermedio', nro:25 , fraseES:'La caja de música tiene una pequeña bailarina', fraseEN:'The music box has a little dancer' },
{ nivel: 'intermedio', nro:26 , fraseES:'El puente de madera cruza el río', fraseEN:'The wooden bridge crosses the river' },
{ nivel: 'intermedio', nro:27 , fraseES:'El tío buscó a sus sobrinos a la salida del colegio', fraseEN:'The uncle looked for his nephews at the school exit' },
{ nivel: 'intermedio', nro:28 , fraseES:'La estudiante está atenta a todas las palabras del profesor', fraseEN:'The female student is aware of all the teacher\'s words' },
{ nivel: 'intermedio', nro:29 , fraseES:'Desde que él tiene insomnio pasa toda la noche despierto', fraseEN:'Since he has insomnia he stays awake all night long' },
{ nivel: 'intermedio', nro:30 , fraseES:'Encontré un cajón lleno de fotos y cartas que pertenecieron a mis abuelos', fraseEN:'I found a drawer full of photos and letters that belonged to my grandparents' },
{ nivel: 'intermedio', nro:31 , fraseES:'La historia fue contradictoria de principio al fin', fraseEN:'The story was contradictory from beginning to end' },
{ nivel: 'intermedio', nro:32 , fraseES:'Un día como cualquier otro, nada presagiaba lo ocurrido con el cantante', fraseEN:'One day like any other, nothing foreshadowed what happened with the singer' },
{ nivel: 'intermedio', nro:33 , fraseES:'Vi mi reflejo en el espejo y quedé complacida con el peinado', fraseEN:'I saw my reflection in the mirror and was pleased with the hairstyle' },
{ nivel: 'intermedio', nro:34 , fraseES:'Esas minas de carbón fueron clausuradas por razones de seguridad', fraseEN:'Those coal mines were closed down for safety reasons' },
{ nivel: 'intermedio', nro:35 , fraseES:'Hay muchas berenjenas en el huerto', fraseEN:'There are a lot of eggplants in the orchard' },
{ nivel: 'intermedio', nro:36 , fraseES:'Trabajé en esa empresa durante cuatro años y medio', fraseEN:'I worked in that company for four and a half years' },
{ nivel: 'intermedio', nro:37 , fraseES:'Ten cuidado, eso parece ser una secta', fraseEN:'Be careful, that looks like a cult' },
{ nivel: 'intermedio', nro:38 , fraseES:'¿Te gustaría salir a cenar conmigo?', fraseEN:'Would you like to go out to dinner with me?' },
{ nivel: 'intermedio', nro:39 , fraseES:'En el coro hay sopranos, contraltos, tenores y bajos', fraseEN:'In the choir there are sopranos, contraltos, tenors and basses.' },
{ nivel: 'intermedio', nro:40 , fraseES:'El extintor funcionó perfectamente y apagó el incendio', fraseEN:'The fire extinguisher worked perfectly and put out the fire' },
{ nivel: 'intermedio', nro:41 , fraseES:'Me gusta mucho el proyecto, quiero formar parte en él', fraseEN:'I really like the project I want to be part of it' },
{ nivel: 'intermedio', nro:42 , fraseES:'Toda la conversación giró en torno a su vida amorosa', fraseEN:'The whole conversation centered around her love life' },
{ nivel: 'intermedio', nro:43 , fraseES:'Por favor lava los platos después de terminar tu comida', fraseEN:'Please wash the dishes after finishing your meal' },
{ nivel: 'intermedio', nro:44 , fraseES:'El fútbol se juega con balón y el beisbol con bate y pelota', fraseEN:'Soccer is played with a soccer ball and baseball with a bat and ball' },
{ nivel: 'intermedio', nro:45 , fraseES:'Acompáñame por favor, no  me gusta estar sola', fraseEN:'Please stay with me, I don\'t like to be alone' },
{ nivel: 'intermedio', nro:46 , fraseES:'Ellas son muy amigas y se apoyan mutuamente', fraseEN:'They are close friends and support each other' },
{ nivel: 'intermedio', nro:47 , fraseES:'No quiero juzgar sobre si tienes o no razón', fraseEN:'I don\'t want to judge whether you are right or wrong' },
{ nivel: 'principiante', nro:1 , fraseES:'Buenos días', fraseEN:'Good morning' },
{ nivel: 'principiante', nro:2 , fraseES:'¿Cómo estás?', fraseEN:'How are you?' },
{ nivel: 'principiante', nro:3 , fraseES:'A ella le gusta cantar', fraseEN:'She likes to sing' },
{ nivel: 'principiante', nro:4 , fraseES:'Busca una camisa', fraseEN:'Search for a shirt' },
{ nivel: 'principiante', nro:5 , fraseES:'Ama la vida', fraseEN:'Love life' },
{ nivel: 'principiante', nro:6 , fraseES:'Te quiero mucho', fraseEN:'I love you so much' },
{ nivel: 'principiante', nro:7 , fraseES:'A mí me gusta comer helado', fraseEN:'I like to eat ice cream' },
{ nivel: 'principiante', nro:8 , fraseES:'Un edificio alto', fraseEN:'A high building' },
{ nivel: 'principiante', nro:9 , fraseES:'Una casa muy bonita', fraseEN:'A very beautiful house' },
{ nivel: 'principiante', nro:10 , fraseES:'Hace mucho sol', fraseEN:'It is very sunny' },
{ nivel: 'principiante', nro:11 , fraseES:'Hoy es un bonito día', fraseEN:'Today is a lovely day' },
{ nivel: 'principiante', nro:12 , fraseES:'Cuéntame un cuento', fraseEN:'Tell me a story' },
{ nivel: 'principiante', nro:13 , fraseES:'Dibuja una flor', fraseEN:'Draw a flower' },
{ nivel: 'principiante', nro:14 , fraseES:'¿Qué hora es?', fraseEN:'What time is it?' },
{ nivel: 'principiante', nro:15 , fraseES:'Quédate en tu casa', fraseEN:'stay in your home' },
{ nivel: 'principiante', nro:16 , fraseES:'Está lloviendo', fraseEN:'It is raining' },
{ nivel: 'principiante', nro:17 , fraseES:'Un vuelo a París', fraseEN:'A flight to Paris' },
{ nivel: 'principiante', nro:18 , fraseES:'Me gusta pintar', fraseEN:'I like to paint' },
{ nivel: 'principiante', nro:19 , fraseES:'El pequeño pony', fraseEN:'The Little Pony' },
{ nivel: 'principiante', nro:20 , fraseES:'Escuchar melodías', fraseEN:'Listening to melodies' },
{ nivel: 'principiante', nro:21 , fraseES:'Un atardecer en la playa', fraseEN:'A sunset on the beach' },
{ nivel: 'principiante', nro:22 , fraseES:'El mar azul', fraseEN:'The blue sea' },
{ nivel: 'principiante', nro:23 , fraseES:'Un árbol verde', fraseEN:'A green tree' },
{ nivel: 'principiante', nro:24 , fraseES:'Una hermosa sonrisa', fraseEN:'A beautiful smile' },
{ nivel: 'principiante', nro:25 , fraseES:'Las páginas del cuaderno', fraseEN:'The pages of the notebook' },
{ nivel: 'principiante', nro:26 , fraseES:'La montaña es muy alta', fraseEN:'The mountain is very high' },
{ nivel: 'principiante', nro:27 , fraseES:'Las teclas del piano', fraseEN:'The piano keys' },
{ nivel: 'principiante', nro:28 , fraseES:'¿Quién eres?', fraseEN:'Who are you?' },
{ nivel: 'principiante', nro:29 , fraseES:'¿Para dónde vas?', fraseEN:'Where are you going?' },
{ nivel: 'principiante', nro:30 , fraseES:'Te estoy buscando', fraseEN:'I am looking for you' },
{ nivel: 'principiante', nro:31 , fraseES:'Una taza de té', fraseEN:'A cup of tea' },
{ nivel: 'principiante', nro:32 , fraseES:'Las fotos son hermosas', fraseEN:'The photos are beautiful' },
{ nivel: 'principiante', nro:33 , fraseES:'Una terapia musical', fraseEN:'A musical therapy' },
{ nivel: 'principiante', nro:34 , fraseES:'El canto de los pájaros', fraseEN:'The singing of the birds' },
{ nivel: 'principiante', nro:35 , fraseES:'La nieve ha cubierto todo el paisaje', fraseEN:'The snow has covered the whole landscape' },
{ nivel: 'principiante', nro:36 , fraseES:'El abrigo azul ', fraseEN:'The blue coat' },
{ nivel: 'principiante', nro:37 , fraseES:'Hay un camino muy largo', fraseEN:'There is a very long road' },
{ nivel: 'principiante', nro:38 , fraseES:'Dulces sueños al dormir', fraseEN:'Sweet dreams of sleep' },
{ nivel: 'principiante', nro:39 , fraseES:'La ropa está en el armario', fraseEN:'The clothes are in the closet' },
{ nivel: 'principiante', nro:40 , fraseES:'Hay flores en el jardín', fraseEN:'There are flowers in the garden' },
{ nivel: 'principiante', nro:41 , fraseES:'Muchas frutas para comer', fraseEN:'Lots of fruits to eat' },
{ nivel: 'principiante', nro:42 , fraseES:'La madre es amorosa', fraseEN:'The mother is loving' },
{ nivel: 'principiante', nro:43 , fraseES:'El libro está escrito en versos', fraseEN:'The book is written in verse' },
{ nivel: 'principiante', nro:44 , fraseES:'No me gusta esa canción', fraseEN:'I don\'t like that song' }

	
];
