// NO SE ESTá UTILIZANDO ACTUALMENTE
// arrays con los textos necesarios para construir la escritura en Portugués

export const CIENPT: string[] = ['UM','DOIS','TRÊS','QUATRO','CINCO','SEIS','SETE','OITO','NOVE','DEZ','ONZE','DOZE','TREZE','CATORZE','QUINZE','DEZASSEIS','DEZASSETE',
'DEZOITO','DEZANOVE','VINTE','VINTE E UM','VINTE E DOIS','VINTE E TRÊS','VINTE E QUATRO','VINTE E CINCO','VINTE E SEIS','VINTE E SETE','VINTE E OITO','VINTE E NOVE',
'TRINTA','TRINTA E UM','TRINTA E DOIS','TRINTA E TRÊS','TRINTA E QUATRO','TRINTA E CINCO','TRINTA E SEIS','TRINTA E SETE','TRINTA E OITO','TRINTA E NOVE',
'QUARENTA','QUARENTA E UM','QUARENTA E DOIS','QUARENTA E TRÊS','QUARENTA E QUATRO','QUARENTA E CINCO','QUARENTA E SEIS','QUARENTA E SETE','QUARENTA E OITO','QUARENTA E NOVE',
'CINQUENTA','CINQUENTA E UM','CINQUENTA E DOIS','CINQUENTA E TRÊS','CINQUENTA E QUATRO','CINQUENTA E CINCO','CINQUENTA E SEIS','CINQUENTA E SETE','CINQUENTA E OITO','CINQUENTA E NOVE',
'SESSENTA','SESSENTA E UM','SESSENTA E DOIS','SESSENTA E TRÊS','SESSENTA E QUATRO','SESSENTA E CINCO','SESSENTA E SEIS','SESSENTA E SETE','SESSENTA E OITO','SESSENTA E NOVE',
'SETENTA','SETENTA E UM','SETENTA E DOIS','SETENTA E TRÊS','SETENTA E QUATRO','SETENTA E CINCO','SETENTA E SEIS','SETENTA E SETE','SETENTA E OITO','SETENTA E NOVE',
'OITENTA','OITENTA E UM','OITENTA E DOIS','OITENTA E TRÊS','OITENTA E QUATRO','OITENTA E CINCO','OITENTA E SEIS','OITENTA E SETE','OITENTA E OITO','OITENTA E NOVE',
'NOVENTA','NOVENTA E UM','NOVENTA E DOIS','NOVENTA E TRÊS','NOVENTA E QUATRO','NOVENTA E CINCO','NOVENTA E SEIS','NOVENTA E SETE','NOVENTA E OITO','NOVENTA E NOVE','CEM',' '
]

export const CENTENASPT: string[] = ['CEM','DUZENTOS','TREZENTOS','QUATROCENTOS','QUINHENTOS','SEISCENTOS','SETECENTOS','OITOCENTOS','NOVECENTOS'
]

export const CENTENASPT1: string[] = ['CENTO E','DUZENTOS E','TREZENTOS E','QUATROCENTOS E','QUINHENTOS E','SEISCENTOS E','SETECENTOS E','OITOCENTOS E','NOVECENTOS E'
]

/* No se están actualizando actualmente
numeroCien:number[]= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
						31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,
							71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,0];
numeroCentenas:number[] = [1,2,3,4,5,6,7,8,9,0]; */