// NO SE ESTá UTILIZANDO ACTUALMENTE
// arrays con los textos necesarios para construir la escritura en Español

export const CIEN: string[] = ['UNO','DOS','TRES','CUATRO','CINCO','SEIS','SIETE','OCHO','NUEVE','DIEZ','ONCE','DOCE','TRECE','CATORCE','QUINCE','DIECISÉIS','DIECISIETE',
'DIECIOCHO','DIECINUEVE','VEINTE','VEINTIUNO','VEINTIDÓS','VEINTITRÉS','VEINTICUATRO','VEINTICINCO','VEINTISÉIS','VEINTISIETE','VEINTIOCHO','VEINTINUEVE',
'TREINTA','TREINTA Y UNO','TREINTA Y DOS','TREINTA Y TRES','TREINTA Y CUATRO','TREINTA Y CINCO','TREINTA Y SEIS','TREINTA Y SIETE','TREINTA Y OCHO','TREINTA Y NUEVE',
'CUARENTA','CUARENTA Y UNO','CUARENTA Y DOS','CUARENTA Y TRES','CUARENTA Y CUATRO','CUARENTA Y CINCO','CUARENTA Y SEIS','CUARENTA Y SIETE','CUARENTA Y OCHO','CUARENTA Y NUEVE',
'CINCUENTA','CINCUENTA Y UNO','CINCUENTA Y DOS','CINCUENTA Y TRES','CINCUENTA Y CUATRO','CINCUENTA Y CINCO','CINCUENTA Y SEIS','CINCUENTA Y SIETE','CINCUENTA Y OCHO','CINCUENTA Y NUEVE',
'SESENTA','SESENTA Y UNO','SESENTA Y DOS','SESENTA Y TRES','SESENTA Y CUATRO','SESENTA Y CINCO','SESENTA Y SEIS','SESENTA Y SIETE','SESENTA Y OCHO','SESENTA Y NUEVE',
'SETENTA','SETENTA Y UNO','SETENTA Y DOS','SETENTA Y TRES','SETENTA Y CUATRO','SETENTA Y CINCO','SETENTA Y SEIS','SETENTA Y SIETE','SETENTA Y OCHO','SETENTA Y NUEVE',
'OCHENTA','OCHENTA Y UNO','OCHENTA Y DOS','OCHENTA Y TRES','OCHENTA Y CUATRO','OCHENTA Y CINCO','OCHENTA Y SEIS','OCHENTA Y SIETE','OCHENTA Y OCHO','OCHENTA Y NUEVE',
'NOVENTA','NOVENTA Y UNO','NOVENTA Y DOS','NOVENTA Y TRES','NOVENTA Y CUATRO','NOVENTA Y CINCO','NOVENTA Y SEIS','NOVENTA Y SIETE','NOVENTA Y OCHO','NOVENTA Y NUEVE',' '
]

export const CIEN1: string[] = ['UN','DOS','TRES','CUATRO','CINCO','SEIS','SIETE','OCHO','NUEVE','DIEZ','ONCE','DOCE','TRECE','CATORCE','QUINCE','DIECISÉIS','DIECISIETE',
'DIECIOCHO','DIECINUEVE','VEINTE','VEINTIÚN','VEINTIDÓS','VEINTITRÉS','VEINTICUATRO','VEINTICINCO','VEINTISÉIS','VEINTISIETE','VEINTIOCHO','VEINTINUEVE',
'TREINTA','TREINTA Y UN','TREINTA Y DOS','TREINTA Y TRES','TREINTA Y CUATRO','TREINTA Y CINCO','TREINTA Y SEIS','TREINTA Y SIETE','TREINTA Y OCHO','TREINTA Y NUEVE',
'CUARENTA','CUARENTA Y UN','CUARENTA Y DOS','CUARENTA Y TRES','CUARENTA Y CUATRO','CUARENTA Y CINCO','CUARENTA Y SEIS','CUARENTA Y SIETE','CUARENTA Y OCHO','CUARENTA Y NUEVE',
'CINCUENTA','CINCUENTA Y UN','CINCUENTA Y DOS','CINCUENTA Y TRES','CINCUENTA Y CUATRO','CINCUENTA Y CINCO','CINCUENTA Y SEIS','CINCUENTA Y SIETE','CINCUENTA Y OCHO','CINCUENTA Y NUEVE',
'SESENTA','SESENTA Y UN','SESENTA Y DOS','SESENTA Y TRES','SESENTA Y CUATRO','SESENTA Y CINCO','SESENTA Y SEIS','SESENTA Y SIETE','SESENTA Y OCHO','SESENTA Y NUEVE',
'SETENTA','SETENTA Y UN','SETENTA Y DOS','SETENTA Y TRES','SETENTA Y CUATRO','SETENTA Y CINCO','SETENTA Y SEIS','SETENTA Y SIETE','SETENTA Y OCHO','SETENTA Y NUEVE',
'OCHENTA','OCHENTA Y UN','OCHENTA Y DOS','OCHENTA Y TRES','OCHENTA Y CUATRO','OCHENTA Y CINCO','OCHENTA Y SEIS','OCHENTA Y SIETE','OCHENTA Y OCHO','OCHENTA Y NUEVE',
'NOVENTA','NOVENTA Y UN','NOVENTA Y DOS','NOVENTA Y TRES','NOVENTA Y CUATRO','NOVENTA Y CINCO','NOVENTA Y SEIS','NOVENTA Y SIETE','NOVENTA Y OCHO','NOVENTA Y NUEVE',' '
]

export const CENTENAS: string[] = ['CIENTO','DOSCIENTOS','TRESCIENTOS','CUATROCIENTOS','QUINIENTOS','SEISCIENTOS','SETECIENTOS','OCHOCIENTOS','NOVECIENTOS',' '
]


/* No se están actualizando actualmente
numeroCien:number[]= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
						31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,
							71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,0];
numeroCentenas:number[] = [1,2,3,4,5,6,7,8,9,0]; */