
export const PTPALABRAS: string[] = [
'A cave',
'Avô',
'A biblioteca tem muitos livros',
'As cordas da harpa',
'Ele escreve muito bem português',
'Arrecadação',   
'estações do ano',
'Não é fácil obter o endereço certo',
'Onde estão os meus lápis?',
'A que horas sais do trabalho?',
'A varanda',
'Regiões',
'Os sapatos são muito bonitos',
'Uma sobremesa com morangos e pêssegos',
'Fechar',
'Corredor',
'Família',
'O programa é perfeito',
'Placa com garfo e faca',
'Eu bebo água',
'A cozinha',
'Partes da casa',
'A placa está suja',
'Os carros antigos',
'Eles vão às montanhas',
'Sala',
'Dezembro',
'Vamos à praia esta tarde',
'Um voo para Paris',
'A senhora não gosta de dançar',
'Quarto',
'Novembro',
'Idade',
'Está a chover',
'O cavalo tem sede',
'Os pinguins não voam',
'Outubro',
'Data de nascimento',
'Ama a vida',
'Primavera, Verão, Outono, Inverno',
'Ela desenha uma flor',
'Setembro',
'Morada',
'Os relógios estão sincronizados',
'Telemóvel',
'Ela usa saltos altos ',
'Agosto',
'Boa noite',
'A sopa está muito fria',
'Adeus Até logo',
'As espirais na natureza',
'Julho',
'Boa tarde',
'Os rebuçados são de menta',
'Olá',
'Ela gosta de sorrir',
'Junho',
'Bom dia',
'Um edifício alto',
'O último dia útil da semana é a sexta-feira',
'há um só cisne no lago',
'Ele gosta de andar',
'Maio',
'Bisneta',
'Eu gosto de comer gelado',
'O primeiro dia útil da semana é a segunda-feira',
'há muitos pombos na praça',
'A casa é muito grande',
'Abril',
'Bisneto',
'As florestas são os pulmões do planeta',
'Os dias da semana',
'o gato é muito gordo',
'O meu avião parte em poucos minutos',
'Março',
'Cunhada',
'Um pôr-do-sol na praia',
'As línguas',
'o cão não tem nome',
'Eu gosto de pintar',
'Fevereiro',
'Cunhado',
'Os alunos estudam para o exame',
'Os países e as cidades',
'Elas não gostam de correr',
'Não se esqueça de fechar',
'Janeiro',
'Prima',
'Eles ficam em casa',
'As raparigas não querem brincar',
'Eles gostam de nadar',
'Ela usa uma fita cor-de-rosa',
'Domingo',
'Primo',
'Ela gosta de cantar',
'As nuvens estão no céu',
'Nós queremos viajar',
'Eu gosto do canto dos pássaros',
'Sábado',
'Sogra',
'Há muitos sóis no universo',
'Os gambás cheiram mal',
'Você caminha muito depressa',
'Ouvir melodias',
'Sexta-feira',
'Sogro',
'A mulher gosta de usar vestidos',
'Ele procura em todo o lado',
'ela tem três gatos',
'Está certo',
'Quinta-feira',
'Nora',
'Eu tenho dois irmãos',
'Uma chávena de chá',
'ele ensina espanhol como segunda língua',
'Este é um livro fácil de ler',
'Quarta-feira',
'Genro',
'Uma árvore verde',
'Eu estou à sua procura',
'Tu olhas da tua janela',
'O estudo do corpo humano',
'Terça-feira',
'Tia',
'As teclas do piano',
'Proibido virar à direita',
'Eu falo com ela todas as manhãs',
'O vento sopra forte',
'Segunda-feira',
'Tio',
'O pequeno pónei',
'As raparigas tocam o piano',
'Quero ir ao centro, por favor',
'O caminho para a cidade',
'Casa de banho',
'Sobrinha',
'O lápis não tem apagador',
'Mede a distância entre dois pontos',
'Qual é o nome desta rua?',
'A que horas funciona o autocarro?',
'Janela',
'Sobrinho',
'Quanto custa a saia?',
'Pincéis, tintas e telas',
'Onde há um restaurante?',
'Temos medo daquele vulcão',
'A porta',
'Irmã',
'Os caranguejos andam de lado e para trás',
'Nós temos fome',
'Qual é o endereço do hotel?',
'Quem é você?',
'Sotão',
'Irmão',
'Os comboios são modernos',
'Hoje é um belo dia',
'A criança tem sede',
'A ponte fica no norte da cidade',
'Garagem',
'Filha',
'Tu tens boa sorte',
'Proibido virar à esquerda',
'Que horas são?',
'Não recordo como se faz isto',
'Telhado',
'Filho',
'As páginas do caderno de notas',
'O rapaz joga com uma bola',
'Um só peixe',
'Eu fico em casa',
'O chão',                                     
'Pai',
'Um lugar desconhecido',
'Eu estou no trabalho',
'Ele repete tudo o que eu digo',
'As fotos não estão no álbum',
'Terraço',                        
'Mãe',
'Mercúrio e Vénus não têm luas',
'O pequeno-almoço é servido',
'O garfo está limpo',
'Por favor não vá',
'Casa',
'Neta',
'O mar azul',
'Está muito ensolarado',
'Tu falas bem alemão',
'Como vai?',
'A parede',
'Neto',
'Para onde vais?',
'Conte-me uma história',
'Eu amo-te muito',
'O sábado e o domingo são os dias do fim de semana',
'Tecto',
'Avó',
'Não queremos fazer os trabalhos de casa',
'Passa a ferro as camisas',
'A montanha é muito alta',
'Pequeno-almoço, almoço e jantar'


];